import type { Category, DirectoryEntry, EntryType, Industry } from "./types";

/**
 * AI agents catalog — personal assistants, coding agents, multi-agent frameworks,
 * browser/research agents, memory/MCP infra, and voice agents.
 * Live GitHub links via `link` + `resourceUrl`. SEO via githubRepo.
 */

type Spec = {
  repo: string;
  name: string;
  type: EntryType;
  categories: Category[];
  industries: Industry[];
  what: string;
  exampleIntro: string;
  steps: string[];
  prompts: [string, string, string];
  prerequisites: string[];
  tips: string[];
  stars: string;
  group: string;
};

function entryFromSpec(spec: Spec): DirectoryEntry {
  const githubUrl = `https://github.com/${spec.repo}`;
  const slug = spec.repo
    .toLowerCase()
    .replace(/\//g, "-")
    .replace(/\./g, "-")
    .replace(/_/g, "-");
  const steps = spec.steps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  return {
    slug,
    name: spec.name,
    type: spec.type,
    githubRepo: spec.repo,
    resourceUrl: githubUrl,
    summary: `${spec.what} GitHub: ${spec.repo} (~${spec.stars} stars).`,
    overview: [
      `${spec.name} (${spec.repo}) is listed in LimeDock Directories as an AI agent resource.`,
      "",
      spec.what,
      "",
      `Group: ${spec.group}. Community size: ~${spec.stars} GitHub stars.`,
      "",
      `Repo (copy/paste): ${githubUrl}`,
      "",
      "This page is a plain-English guide so searches for the GitHub project can land on how teams actually use it.",
    ].join("\n"),
    categories: spec.categories,
    industries: spec.industries,
    link: githubUrl,
    installation: [
      "Open the GitHub repository, then follow the README for your stack.",
      "",
      `Official GitHub repository: ${githubUrl}`,
      `GitHub path: ${spec.repo}`,
      "",
      "How to open it:",
      `1. Copy: ${githubUrl}`,
      "2. Clone or follow the README for your OS/stack.",
      "3. Start with the smallest example before production use.",
    ].join("\n"),
    howToUse: ["**Simple example**", spec.exampleIntro, "", steps].join("\n"),
    useCases: [
      `Evaluate ${spec.repo} as an AI agent building block`,
      `Pilot ${spec.name} on one staging workflow`,
      "Compare against agents you already pay for",
      "Document a team playbook after the pilot",
    ],
    examplePrompts: [...spec.prompts],
    prerequisites: spec.prerequisites,
    tips: spec.tips,
    sources: [],
  };
}

const SPECS: Spec[] = [
  {
    repo: "lobehub/lobehub",
    name: "LobeHub",
    type: "agent",
    categories: ["product", "operations", "engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Chief Agent Operator / agent workspace for running and managing AI agents.",
    exampleIntro: "You want one workspace to operate multiple agents instead of juggling tabs.",
    steps: ["Clone or install LobeHub per the README.", "Connect your model providers.", "Create one agent role (research, support, coding) and run a real task with review."],
    prompts: ["Set up LobeHub as our team agent workspace.", "How is LobeHub different from Open WebUI?", "Create a support agent persona in LobeHub."] as Spec["prompts"],
    prerequisites: ["Model API keys or local runtime", "Clear agent roles"],
    tips: ["Start with one agent role.", "Keep humans approving customer-facing sends."],
    stars: "81k",
    group: "personal-assistants",
  },
  {
    repo: "ChatGPTNextWeb/NextChat",
    name: "NextChat",
    type: "agent",
    categories: ["product", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Fast multi-platform AI assistant UI (ChatGPT-style) you can deploy yourself.",
    exampleIntro: "The team wants a private ChatGPT-like app on web/desktop without rebuilding a UI.",
    steps: ["Deploy NextChat (Docker or Vercel-style per docs).", "Add your API keys / providers.", "Share with the team behind auth/VPN."],
    prompts: ["Deploy NextChat for our internal assistants.", "NextChat vs LibreChat vs Open WebUI?", "Lock down auth before public exposure."] as Spec["prompts"],
    prerequisites: ["Hosting", "Provider keys", "Auth plan"],
    tips: ["Don\u2019t expose without authentication.", "Pin model choices so costs don\u2019t surprise you."],
    stars: "89k",
    group: "personal-assistants",
  },
  {
    repo: "HKUDS/nanobot",
    name: "Nanobot",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Lightweight self-hosted personal agent \u2014 small footprint, yours to run.",
    exampleIntro: "You want a personal agent on a cheap VPS without a heavyweight stack.",
    steps: ["Clone HKUDS/nanobot.", "Follow the self-host install.", "Give it one recurring job (daily briefing) with tight tool permissions."],
    prompts: ["Install nanobot on a $5 VPS for a morning briefing.", "What tools should nanobot get on day one?", "Nanobot vs Hermes for a solo founder?"] as Spec["prompts"],
    prerequisites: ["Small server or laptop", "Model access"],
    tips: ["Least privilege on tools.", "One reliable job beats ten flaky ones."],
    stars: "47k",
    group: "personal-assistants",
  },
  {
    repo: "danny-avila/LibreChat",
    name: "LibreChat",
    type: "agent",
    categories: ["product", "operations", "engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "ChatGPT-style clone with agents, multi-provider chat, and MCP support.",
    exampleIntro: "You need an open ChatGPT alternative that can grow into agents + tools.",
    steps: ["Deploy LibreChat.", "Configure providers.", "Enable an agent/MCP path for one internal workflow."],
    prompts: ["Deploy LibreChat with OpenAI + one local model.", "How do we enable MCP tools in LibreChat?", "LibreChat vs Open WebUI for agents?"] as Spec["prompts"],
    prerequisites: ["Docker/hosting", "API keys"],
    tips: ["Turn on agents only after basic chat is stable.", "Audit MCP servers before connecting."],
    stars: "42k",
    group: "personal-assistants",
  },
  {
    repo: "janhq/jan",
    name: "Jan",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Offline ChatGPT alternative \u2014 run models locally with a desktop-friendly app.",
    exampleIntro: "You want local chat with no data leaving the machine.",
    steps: ["Install Jan for your OS.", "Download a small local model first.", "Chat offline; only then connect optional remote providers."],
    prompts: ["Install Jan and pull a beginner local model.", "Jan vs Ollama+Open WebUI?", "When is offline Jan the right default for our team?"] as Spec["prompts"],
    prerequisites: ["Enough RAM/disk", "Desktop machine"],
    tips: ["Start tiny on model size.", "Great for privacy-sensitive drafting."],
    stars: "44k",
    group: "personal-assistants",
  },
  {
    repo: "elizaOS/eliza",
    name: "Eliza OS",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Agentic OS for building and running autonomous agents with character/runtime patterns.",
    exampleIntro: "You\u2019re experimenting with always-on autonomous agents beyond a single chat thread.",
    steps: ["Clone elizaOS/eliza.", "Follow the quickstart.", "Run one character/agent with limited capabilities in a sandbox."],
    prompts: ["Explain Eliza OS like I\u2019m a PM.", "Run a minimal Eliza agent safely.", "Where do humans stay in the loop?"] as Spec["prompts"],
    prerequisites: ["Node/runtime per docs", "Sandbox mindset"],
    tips: ["Autonomy without scope = chaos.", "Sandbox credentials only."],
    stars: "19k",
    group: "personal-assistants",
  },
  {
    repo: "SillyTavern/SillyTavern",
    name: "SillyTavern",
    type: "agent",
    categories: ["product", "other"] as Category[],
    industries: ["other", "saas"] as Industry[],
    what: "Power-user LLM front-end for characters, presets, and advanced chat workflows.",
    exampleIntro: "You need a flexible front-end for character-based or highly customized LLM sessions.",
    steps: ["Install SillyTavern per README.", "Connect a backend (local or API).", "Create a character/preset for a specific use case \u2014 then keep it non-customer-facing unless reviewed."],
    prompts: ["Set up SillyTavern with a local model backend.", "When is SillyTavern the wrong tool for business chat?", "Export a reusable character preset."] as Spec["prompts"],
    prerequisites: ["Local or API backend", "Clear usage policy"],
    tips: ["Separate personal RP setups from company data.", "Don\u2019t paste secrets into character cards."],
    stars: "32k",
    group: "personal-assistants",
  },
  {
    repo: "anomalyco/opencode",
    name: "OpenCode",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Open-source coding agent for building software with an agent in the loop.",
    exampleIntro: "You want a coding agent that isn\u2019t locked to one vendor\u2019s CLI.",
    steps: ["Clone anomalyco/opencode.", "Install per README.", "Point it at a sample repo with a small issue and review the diff."],
    prompts: ["Run OpenCode on this good-first-issue.", "OpenCode vs Claude Code vs Codex?", "Sandboxing checklist for coding agents."] as Spec["prompts"],
    prerequisites: ["Git repo", "Model keys", "Code review process"],
    tips: ["Always review diffs.", "Least-privilege tokens."],
    stars: "196k",
    group: "coding-agents",
  },
  {
    repo: "anthropics/claude-code",
    name: "Claude Code",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "Anthropic\u2019s terminal coding agent \u2014 agentic coding with Claude in your repo.",
    exampleIntro: "Your default coding agent should live in the terminal next to git.",
    steps: ["Install Claude Code per Anthropic\u2019s docs.", "Authenticate.", "Open a repo and ask it to fix a failing test with a plan first."],
    prompts: ["Install Claude Code and explain this repository.", "Use Claude Code to draft a PR for this bug.", "How do we add project skills for Claude Code?"] as Spec["prompts"],
    prerequisites: ["Anthropic access", "Terminal", "Git hygiene"],
    tips: ["Commit before long agent runs.", "Use CLAUDE.md / skills for house rules."],
    stars: "141k",
    group: "coding-agents",
  },
  {
    repo: "openai/codex",
    name: "OpenAI Codex CLI",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "OpenAI\u2019s terminal coding agent for repo-aware software tasks.",
    exampleIntro: "You want OpenAI\u2019s coding agent in the CLI alongside your editor.",
    steps: ["Install the Codex CLI per OpenAI docs.", "Auth with your OpenAI account.", "Run a narrow task; review every file change."],
    prompts: ["Install Codex CLI and summarize this codebase.", "Codex vs Claude Code for our stack?", "Safe defaults for allowing shell tools."] as Spec["prompts"],
    prerequisites: ["OpenAI access", "Clean git state"],
    tips: ["Narrow tasks beat \u201crewrite the app.\u201d", "Human review required."],
    stars: "105k",
    group: "coding-agents",
  },
  {
    repo: "openinterpreter/openinterpreter",
    name: "Open Interpreter",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Coding agent oriented around open models \u2014 natural language to code execution locally.",
    exampleIntro: "You want an agent that can run code locally with open-model backends.",
    steps: ["Install Open Interpreter per README.", "Configure a local or API model.", "Start in a safe directory with confirmation mode on."],
    prompts: ["Install Open Interpreter with a local model.", "Run a data-cleaning script via Open Interpreter with confirmations.", "When to prefer Open Interpreter vs Claude Code?"] as Spec["prompts"],
    prerequisites: ["Python env", "Model backend", "Confirm-before-run discipline"],
    tips: ["Never auto-approve shell in prod dirs.", "Use a scratch folder first."],
    stars: "68k",
    group: "coding-agents",
  },
  {
    repo: "cline/cline",
    name: "Cline",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "Autonomous coding agent available as IDE extension, CLI, and SDK.",
    exampleIntro: "You want an autonomous coding agent inside the editor with clear tool use.",
    steps: ["Install Cline in your IDE (or CLI/SDK per docs).", "Connect a model provider.", "Give a small ticket; approve tool calls deliberately."],
    prompts: ["Install Cline in VS Code/Cursor and fix this failing test.", "Cline vs Continue vs Aider?", "Team policy for approving Cline tool calls."] as Spec["prompts"],
    prerequisites: ["IDE", "Model keys"],
    tips: ["Approval mode until you trust the loop.", "Keep secrets out of prompts."],
    stars: "66k",
    group: "coding-agents",
  },
  {
    repo: "aaif-goose/goose",
    name: "Goose",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Extensible agent that goes beyond autocomplete \u2014 recipes and tools for real work.",
    exampleIntro: "You want an extensible coding agent with recipes, not only inline suggestions.",
    steps: ["Install Goose per aaif-goose/goose docs.", "Try a starter recipe.", "Add one custom tool/recipe for your repo."],
    prompts: ["Install Goose and run a starter recipe on this repo.", "How do Goose recipes work?", "Goose vs Aider for pair programming?"] as Spec["prompts"],
    prerequisites: ["Supported runtime", "Model access"],
    tips: ["Recipes encode process \u2014 write them down.", "Extend carefully with reviewed tools."],
    stars: "53k",
    group: "coding-agents",
  },
  {
    repo: "Aider-AI/aider",
    name: "Aider",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "AI pair programming in the terminal \u2014 edits your git repo with commit-friendly workflows.",
    exampleIntro: "You want terminal pair-programming that proposes diffs and commits cleanly.",
    steps: ["Install Aider.", "Run it inside a git repo.", "Ask for a small change; review the diff; let it commit if you like the flow."],
    prompts: ["Use Aider to add tests for this function.", "Aider architect mode vs default?", "How do we keep Aider commits reviewable?"] as Spec["prompts"],
    prerequisites: ["Git repo", "Model API keys"],
    tips: ["Small commits.", "Look at the diff every time."],
    stars: "48k",
    group: "coding-agents",
  },
  {
    repo: "continuedev/continue",
    name: "Continue",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "Open-source coding agent / autopilot that plugs into your IDE.",
    exampleIntro: "You want an open coding assistant in the IDE you can customize and self-host models for.",
    steps: ["Install the Continue extension.", "Configure providers/models.", "Use chat + edit on one file; then try agent mode on a small task."],
    prompts: ["Set up Continue with our OpenAI-compatible endpoint.", "Continue vs Cline for autonomous tasks?", "Share a Continue config with the team."] as Spec["prompts"],
    prerequisites: ["IDE", "Model endpoint"],
    tips: ["Check in useful config, not API keys.", "Start with chat+edit before full autonomy."],
    stars: "35k",
    group: "coding-agents",
  },
  {
    repo: "TabbyML/tabby",
    name: "Tabby",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Self-hosted AI coding assistant \u2014 autocomplete and assistant features on your infra.",
    exampleIntro: "Security wants coding AI without sending code to a public SaaS.",
    steps: ["Deploy Tabby.", "Point the IDE extension at your Tabby server.", "Index allowed repos only."],
    prompts: ["Deploy Tabby for our eng team\u2019s self-hosted autocomplete.", "Tabby vs cloud Copilot for compliance?", "Which repos should be excluded from indexing?"] as Spec["prompts"],
    prerequisites: ["GPU/CPU server", "IDE extensions", "Access control"],
    tips: ["Scope indexed code carefully.", "Measure suggestion accept rates."],
    stars: "34k",
    group: "coding-agents",
  },
  {
    repo: "charmbracelet/crush",
    name: "Crush",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Agentic coding for everyone \u2014 approachable agentic coding UX from Charmbracelet.",
    exampleIntro: "You want an approachable agentic coding tool with great terminal UX.",
    steps: ["Install Crush per the repo.", "Run it on a sample project.", "Complete one small feature with review."],
    prompts: ["Install Crush and walk through a first session.", "Crush vs Aider for beginners?", "How do we teach juniors to review agent diffs?"] as Spec["prompts"],
    prerequisites: ["Terminal comfort", "Model access"],
    tips: ["UX helps adoption \u2014 process still needs review.", "Keep tasks small."],
    stars: "27k",
    group: "coding-agents",
  },
  {
    repo: "PrimeIntellect-ai/prime-agent",
    name: "Prime Agent",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Self-improving long-running coding agent designed for extended autonomous work.",
    exampleIntro: "You want an agent that can run longer coding arcs and improve over time \u2014 with supervision.",
    steps: ["Follow Prime Agent setup.", "Start with a bounded long task in a sandbox repo.", "Inspect artifacts/logs; don\u2019t leave write access to prod."],
    prompts: ["Run Prime Agent on a sandbox refactor with a time box.", "What makes it \u201cself-improving\u201d?", "Guardrails for long-running coding agents."] as Spec["prompts"],
    prerequisites: ["Sandbox repo", "Compute budget", "Human checkpoints"],
    tips: ["Time-box long runs.", "No production credentials."],
    stars: "12k",
    group: "coding-agents",
  },
  {
    repo: "gptme/gptme",
    name: "gptme",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Terminal agent with local tools \u2014 chat that can use your machine\u2019s tools carefully.",
    exampleIntro: "You want a minimal terminal agent that can use local tools without a huge framework.",
    steps: ["Install gptme.", "Enable only the tools you need.", "Run a file-edit task with confirmation."],
    prompts: ["Install gptme and list available tools.", "Use gptme to rename symbols in this folder safely.", "gptme vs Aider?"] as Spec["prompts"],
    prerequisites: ["Python/terminal", "Tool allowlist discipline"],
    tips: ["Disable dangerous tools by default.", "Great for learning agent tool use."],
    stars: "4.4k",
    group: "coding-agents",
  },
  {
    repo: "pingdotgg/t3code",
    name: "T3 Code",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Rising coding agent stack from the T3 / pingdotgg ecosystem.",
    exampleIntro: "You\u2019re exploring a modern coding-agent stack aligned with the T3 community.",
    steps: ["Clone pingdotgg/t3code.", "Follow the quickstart.", "Try it on a TypeScript app and review outputs."],
    prompts: ["Set up t3code for our Next.js app.", "What problems is t3code optimizing for?", "Compare t3code to Claude Code for TS work."] as Spec["prompts"],
    prerequisites: ["TypeScript app", "Model keys"],
    tips: ["Fast-moving \u2014 pin versions.", "Review like any other coding agent."],
    stars: "18k",
    group: "coding-agents",
  },
  {
    repo: "google/skills",
    name: "Google Skills",
    type: "skill",
    categories: ["engineering", "operations", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Google Cloud / product agent skills for coding agents working with Google services.",
    exampleIntro: "Your agent needs grounded playbooks for Google Cloud/product workflows.",
    steps: ["Clone google/skills.", "Install the skills relevant to your GCP products.", "Ask the agent to use the skill for a real Cloud task in a non-prod project."],
    prompts: ["Install Google skills for Cloud Run + IAM basics.", "Which google/skills should a SaaS on GCP enable?", "Safe prompts for non-prod GCP changes."] as Spec["prompts"],
    prerequisites: ["GCP project (non-prod)", "Agent Skills host"],
    tips: ["Never point agents at prod first.", "Audit skills like IAM policies."],
    stars: "17k",
    group: "agent-skills",
  },
  {
    repo: "FoundationAgents/MetaGPT",
    name: "MetaGPT",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Multi-agent \u201cAI software company\u201d \u2014 roles collaborate to generate software artifacts.",
    exampleIntro: "You want to see multi-agent role play (PM/eng/QA) produce a software plan/code sketch.",
    steps: ["Install MetaGPT.", "Run a simple product requirement through the company roles.", "Treat output as draft \u2014 human-architect the real system."],
    prompts: ["Run MetaGPT on a one-paragraph product idea.", "MetaGPT vs ChatDev vs CrewAI?", "What should humans still decide?"] as Spec["prompts"],
    prerequisites: ["Python env", "LLM keys"],
    tips: ["Great for drafts, not autopilot shipping.", "Constrain scope tightly."],
    stars: "70k",
    group: "multi-agent",
  },
  {
    repo: "microsoft/autogen",
    name: "AutoGen",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Microsoft\u2019s multi-agent programming framework for conversational and tool-using agents.",
    exampleIntro: "You need to code multi-agent conversations with solid abstractions.",
    steps: ["Install AutoGen.", "Run a two-agent example.", "Adapt to one internal workflow with logging."],
    prompts: ["Build a two-agent AutoGen planner+executor demo.", "AutoGen vs LangGraph for our services?", "Observability tips for AutoGen apps."] as Spec["prompts"],
    prerequisites: ["Python", "API keys"],
    tips: ["Log every agent message in staging.", "Put budgets on loops."],
    stars: "60k",
    group: "multi-agent",
  },
  {
    repo: "crewAIInc/crewAI",
    name: "CrewAI",
    type: "agent",
    categories: ["engineering", "operations", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "Role-playing collaborative agents \u2014 crews with tasks, tools, and process.",
    exampleIntro: "You want named roles (researcher, writer, reviewer) collaborating on a deliverable.",
    steps: ["Install CrewAI.", "Define a 2\u20133 agent crew.", "Run on a content or research task; review the final artifact."],
    prompts: ["Create a CrewAI crew for competitive research \u2192 brief.", "CrewAI vs AutoGen?", "How do we add human approval steps?"] as Spec["prompts"],
    prerequisites: ["Python", "Tools/API keys"],
    tips: ["Too many roles slows you down \u2014 start with 2.", "Review the final doc always."],
    stars: "57k",
    group: "multi-agent",
  },
  {
    repo: "agno-agi/agno",
    name: "Agno",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Build, run, and manage agent platforms with a developer-friendly agent framework.",
    exampleIntro: "You\u2019re standing up an agent platform, not just a single script.",
    steps: ["Install Agno.", "Create one agent with tools.", "Add memory/storage per docs; deploy a staging endpoint."],
    prompts: ["Scaffold an Agno agent with web search + our API tool.", "Agno vs LangGraph for platform building?", "Deployment checklist."] as Spec["prompts"],
    prerequisites: ["Python/TS per docs", "Hosting"],
    tips: ["Platform thinking early pays off.", "Auth and tenancy before public."],
    stars: "42k",
    group: "multi-agent",
  },
  {
    repo: "langchain-ai/langgraph",
    name: "LangGraph",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Stateful, resilient agent graphs \u2014 cycles, persistence, and control flow for agents.",
    exampleIntro: "Simple chains aren\u2019t enough; you need stateful agent graphs with retries.",
    steps: ["Install LangGraph.", "Build a small graph with a loop + human breakpoint.", "Add persistence for crash recovery."],
    prompts: ["Build a LangGraph support agent with a human-approval node.", "LangGraph vs CrewAI?", "How do checkpoints work?"] as Spec["prompts"],
    prerequisites: ["Python", "LangChain familiarity helps"],
    tips: ["Explicit state beats hidden prompts.", "Add evals on graph paths."],
    stars: "39k",
    group: "multi-agent",
  },
  {
    repo: "reworkd/AgentGPT",
    name: "AgentGPT",
    type: "agent",
    categories: ["product", "engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Browser-deployable autonomous agents \u2014 goal in, multi-step agent out.",
    exampleIntro: "You want a browser UI to spin up autonomous agents for demos and experiments.",
    steps: ["Run AgentGPT locally or use a deployment.", "Give a narrow goal.", "Watch steps; stop when it drifts."],
    prompts: ["Demo AgentGPT with a narrow research goal.", "AgentGPT vs AutoGPT today?", "How do we keep goals sandboxed?"] as Spec["prompts"],
    prerequisites: ["LLM keys", "Browser"],
    tips: ["Demos \u2260 production ops.", "Narrow goals only."],
    stars: "36k",
    group: "multi-agent",
  },
  {
    repo: "OpenBMB/ChatDev",
    name: "ChatDev",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "LLM multi-agent software collaboration \u2014 agents act as a software team.",
    exampleIntro: "You want a multi-agent software team simulation for scaffolding ideas.",
    steps: ["Install ChatDev.", "Provide a simple software requirement.", "Collect artifacts; rewrite for production standards."],
    prompts: ["Run ChatDev on a todo-app requirement.", "ChatDev vs MetaGPT?", "What artifacts are worth keeping?"] as Spec["prompts"],
    prerequisites: ["Python", "LLM keys"],
    tips: ["Use for ideation/scaffolds.", "Humans own architecture."],
    stars: "34k",
    group: "multi-agent",
  },
  {
    repo: "openai/openai-agents-python",
    name: "OpenAI Agents SDK",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Official OpenAI Python SDK for multi-agent applications.",
    exampleIntro: "You\u2019re standardizing on OpenAI\u2019s official agents SDK for Python services.",
    steps: ["Install openai-agents.", "Run the quickstart multi-agent example.", "Wrap with your auth, logging, and evals."],
    prompts: ["Scaffold a Python service with OpenAI Agents SDK.", "Agents SDK vs LangGraph?", "Tracing and guardrails basics."] as Spec["prompts"],
    prerequisites: ["Python", "OpenAI API access"],
    tips: ["Official SDKs still need product guardrails.", "Add tracing day one."],
    stars: "29k",
    group: "multi-agent",
  },
  {
    repo: "huggingface/smolagents",
    name: "Smolagents",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Barebones code-thinking agents from Hugging Face \u2014 minimal agent loops.",
    exampleIntro: "You want a tiny agent framework to learn/hack without a huge stack.",
    steps: ["Install smolagents.", "Run a code-agent example.", "Point tools at safe local functions only."],
    prompts: ["Build a smolagents code agent that uses a calculator tool.", "Smolagents vs LangChain agents?", "Teaching exercise for our eng team."] as Spec["prompts"],
    prerequisites: ["Python", "HF/Open model access optional"],
    tips: ["Minimalism is the point \u2014 don\u2019t re-add bloat.", "Sandbox code execution."],
    stars: "29k",
    group: "multi-agent",
  },
  {
    repo: "agentscope-ai/agentscope",
    name: "AgentScope",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Visible, trustworthy agent runtime focused on transparency and control.",
    exampleIntro: "You need an agent runtime that emphasizes visibility and trustworthiness.",
    steps: ["Install AgentScope.", "Run a visible multi-agent example.", "Add logging your compliance team can read."],
    prompts: ["Explain AgentScope\u2019s trust features simply.", "Build a two-agent demo with full message visibility.", "AgentScope vs AutoGen?"] as Spec["prompts"],
    prerequisites: ["Python", "LLM keys"],
    tips: ["Visibility is a feature \u2014 keep traces.", "Good fit when audit matters."],
    stars: "29k",
    group: "multi-agent",
  },
  {
    repo: "microsoft/semantic-kernel",
    name: "Semantic Kernel",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Microsoft\u2019s enterprise-oriented agent/LLM app framework (.NET/Python).",
    exampleIntro: "You\u2019re in a Microsoft stack and want a first-party agent framework.",
    steps: ["Install Semantic Kernel for your language.", "Create a plugin/tool.", "Build a thin agent API with enterprise auth."],
    prompts: ["Create a Semantic Kernel plugin for our CRM lookup.", "SK vs AutoGen for enterprise .NET?", "Prompt + plan patterns in SK."] as Spec["prompts"],
    prerequisites: [".NET or Python", "Azure/OpenAI access common"],
    tips: ["Enterprise auth/identity early.", "Keep plugins small and tested."],
    stars: "28k",
    group: "multi-agent",
  },
  {
    repo: "mastra-ai/mastra",
    name: "Mastra",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "TypeScript agent framework for building agents in the TS/Node world.",
    exampleIntro: "Your team is TypeScript-first and wants agents in the same language as the app.",
    steps: ["Install Mastra.", "Scaffold an agent with tools.", "Deploy beside your Next/Node services."],
    prompts: ["Scaffold a Mastra agent for support triage.", "Mastra vs LangGraph.js?", "Type-safe tool definitions example."] as Spec["prompts"],
    prerequisites: ["Node/TS", "Model keys"],
    tips: ["TS end-to-end reduces context switching.", "Share types with your API."],
    stars: "27k",
    group: "multi-agent",
  },
  {
    repo: "deepset-ai/haystack",
    name: "Haystack",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Production AI orchestration \u2014 pipelines for RAG and agent-style apps.",
    exampleIntro: "You need production-grade RAG/orchestration with clear pipelines.",
    steps: ["Install Haystack.", "Build a retrieve\u2192generate pipeline.", "Evaluate on your own questions before tools/agents."],
    prompts: ["Build a Haystack RAG pipeline on our docs.", "Haystack vs LlamaIndex?", "Where agents fit in Haystack pipelines."] as Spec["prompts"],
    prerequisites: ["Python", "Document corpus"],
    tips: ["Evals before fancy agents.", "Production = monitoring + fallbacks."],
    stars: "26k",
    group: "multi-agent",
  },
  {
    repo: "google/adk-python",
    name: "Google ADK",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Google Agent Development Kit (Python) for building agents on Google\u2019s stack.",
    exampleIntro: "You\u2019re building agents intended to run with Google\u2019s ADK patterns.",
    steps: ["Install google-adk / follow adk-python docs.", "Run the hello-agent sample.", "Add one tool backed by a Google API in non-prod."],
    prompts: ["Create a hello agent with Google ADK.", "ADK vs LangGraph for GCP teams?", "Non-prod tool permissions checklist."] as Spec["prompts"],
    prerequisites: ["Python", "GCP project"],
    tips: ["Non-prod first always.", "Use IAM least privilege."],
    stars: "21k",
    group: "multi-agent",
  },
  {
    repo: "pydantic/pydantic-ai",
    name: "Pydantic AI",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Typed agent framework from the Pydantic team \u2014 structured outputs and tools.",
    exampleIntro: "You want agents with strict typed outputs, not free-form JSON hopes.",
    steps: ["Install pydantic-ai.", "Define a typed result model.", "Build an agent that must return that shape."],
    prompts: ["Build a pydantic-ai agent that returns a typed ticket triage object.", "Why typed agents beat stringly prompts?", "Pydantic AI vs OpenAI Agents SDK?"] as Spec["prompts"],
    prerequisites: ["Python", "Pydantic familiarity"],
    tips: ["Types are guardrails \u2014 use them.", "Validate at boundaries."],
    stars: "19k",
    group: "multi-agent",
  },
  {
    repo: "camel-ai/camel",
    name: "CAMEL",
    type: "agent",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    what: "Multi-agent research framework for studying communicative agents.",
    exampleIntro: "You\u2019re researching multi-agent communication patterns, not only shipping a chatbot.",
    steps: ["Install CAMEL.", "Run a role-playing agent example.", "Log dialogues for analysis."],
    prompts: ["Run a CAMEL role-play experiment for a research note.", "CAMEL vs CrewAI for research?", "What metrics should we capture?"] as Spec["prompts"],
    prerequisites: ["Python", "Research mindset"],
    tips: ["Research frameworks \u2260 product runtime by default.", "Capture transcripts."],
    stars: "18k",
    group: "multi-agent",
  },
  {
    repo: "TransformerOptimus/SuperAGI",
    name: "SuperAGI",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Dev-first autonomous agent framework with tooling for building agent apps.",
    exampleIntro: "You want a developer-oriented autonomous agent framework with a toolkit.",
    steps: ["Install SuperAGI.", "Run a sample agent.", "Constrain tools; add your own carefully."],
    prompts: ["Run SuperAGI\u2019s sample agent with read-only tools.", "SuperAGI vs AutoGPT lineage?", "Production pitfalls of autonomous agents."] as Spec["prompts"],
    prerequisites: ["Docker/Python per docs", "Keys"],
    tips: ["Read-only tools first.", "Watch loop costs."],
    stars: "18k",
    group: "multi-agent",
  },
  {
    repo: "QwenLM/Qwen-Agent",
    name: "Qwen-Agent",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Agent applications framework built around Qwen models.",
    exampleIntro: "You\u2019re standardizing on Qwen and want a first-party agent stack.",
    steps: ["Install Qwen-Agent.", "Connect a Qwen endpoint.", "Build a tool-using agent for one internal task."],
    prompts: ["Build a Qwen-Agent with a docs QA tool.", "Qwen-Agent vs generic LangChain?", "Deployment notes for Qwen endpoints."] as Spec["prompts"],
    prerequisites: ["Qwen model access", "Python"],
    tips: ["Match agent framework to model family when it helps.", "Eval in your language/domain."],
    stars: "17k",
    group: "multi-agent",
  },
  {
    repo: "alibaba/spring-ai-alibaba",
    name: "Spring AI Alibaba",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Java agentic AI framework in the Spring ecosystem.",
    exampleIntro: "Your backend is Java/Spring and you want agent patterns without leaving the JVM world.",
    steps: ["Add the Spring AI Alibaba dependencies.", "Create a simple agent bean/service.", "Expose behind your existing Spring security."],
    prompts: ["Scaffold a Spring AI Alibaba agent service.", "Java agent options vs Python frameworks?", "Security integration checklist."] as Spec["prompts"],
    prerequisites: ["Java/Spring", "Model endpoint"],
    tips: ["Reuse your Spring security model.", "Don\u2019t bypass auth for demos in shared envs."],
    stars: "11k",
    group: "multi-agent",
  },
  {
    repo: "MervinPraison/PraisonAI",
    name: "PraisonAI",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "Production-oriented multi-agent workforce framework.",
    exampleIntro: "You want a multi-agent \u201cworkforce\u201d framing for production tasks.",
    steps: ["Install PraisonAI.", "Define a small workforce.", "Run one production-like job in staging with logs."],
    prompts: ["Create a PraisonAI workforce for research\u2192draft\u2192QA.", "PraisonAI vs CrewAI?", "Production logging requirements."] as Spec["prompts"],
    prerequisites: ["Python", "Staging env"],
    tips: ["Workforce metaphors need owners.", "Staging first."],
    stars: "8.8k",
    group: "multi-agent",
  },
  {
    repo: "kyegomez/swarms",
    name: "Swarms",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Enterprise multi-agent orchestration framework (swarms of agents).",
    exampleIntro: "You need orchestration patterns for many agents cooperating at scale.",
    steps: ["Install swarms.", "Run a small swarm example.", "Add rate limits and observability before scaling out."],
    prompts: ["Build a 3-agent swarm for document processing.", "Swarms vs LangGraph for orchestration?", "Failure modes when scaling agent swarms."] as Spec["prompts"],
    prerequisites: ["Python", "Budget for many LLM calls"],
    tips: ["Swarms multiply cost \u2014 meter everything.", "Start with 2\u20133 agents."],
    stars: "7.0k",
    group: "multi-agent",
  },
  {
    repo: "embabel/embabel-agent",
    name: "Embabel Agent",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "JVM agent framework for building agents on the JVM.",
    exampleIntro: "Kotlin/Java teams want an agent framework that fits JVM services.",
    steps: ["Clone embabel-agent.", "Follow the JVM quickstart.", "Wrap an internal API as a tool."],
    prompts: ["Create a JVM agent with Embabel that calls our HTTP API.", "Embabel vs Spring AI Alibaba?", "Packaging tips for JVM agents."] as Spec["prompts"],
    prerequisites: ["JVM toolchain", "Model access"],
    tips: ["Fit your existing deploy pipeline.", "Typed tools help."],
    stars: "4.1k",
    group: "multi-agent",
  },
  {
    repo: "unclebob/swarm-forge",
    name: "Swarm Forge",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Coordinate several AI agents \u2014 forging a swarm with structure.",
    exampleIntro: "You want a structured way to coordinate multiple agents on one objective.",
    steps: ["Clone swarm-forge.", "Read the coordination model.", "Run a multi-agent exercise on a toy problem."],
    prompts: ["Explain Swarm Forge\u2019s coordination model simply.", "Run a toy multi-agent coding task.", "How do we prevent agent deadlocks?"] as Spec["prompts"],
    prerequisites: ["Willingness to read the model", "LLM keys"],
    tips: ["Coordination > more agents.", "Toy problems first."],
    stars: "2.1k",
    group: "multi-agent",
  },
  {
    repo: "bytedance/UI-TARS-desktop",
    name: "UI-TARS Desktop",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Multimodal GUI agent stack as a desktop app \u2014 agents that operate UIs.",
    exampleIntro: "You need agents that click/operate desktop or GUI environments, not only browsers/APIs.",
    steps: ["Install UI-TARS Desktop per docs.", "Run on a staging app UI.", "Limit permissions; log every action."],
    prompts: ["Set up UI-TARS Desktop against our staging Electron app.", "UI-TARS Desktop vs browser-use?", "Safety checklist for GUI agents."] as Spec["prompts"],
    prerequisites: ["Desktop OS support", "Staging apps"],
    tips: ["GUI agents are powerful and risky.", "Never prod admin UIs first."],
    stars: "39k",
    group: "browser-research",
  },
  {
    repo: "assafelovic/gpt-researcher",
    name: "GPT Researcher",
    type: "agent",
    categories: ["engineering", "marketing", "product"] as Category[],
    industries: ["saas", "agency", "education", "other"] as Industry[],
    what: "Autonomous deep-research agent that gathers sources and writes research reports.",
    exampleIntro: "You need thorough research briefs without a human spending half a day tab-hopping.",
    steps: ["Install GPT Researcher.", "Give a sharp research question.", "Require citations; fact-check before publishing."],
    prompts: ["Research \u201cAI SEO for B2B SaaS\u201d with GPT Researcher.", "How do we enforce citations?", "GPT Researcher vs plain ChatGPT browsing?"] as Spec["prompts"],
    prerequisites: ["API keys", "Time to verify sources"],
    tips: ["Treat as draft research.", "Verify primary sources."],
    stars: "29k",
    group: "browser-research",
  },
  {
    repo: "browserbase/stagehand",
    name: "Stagehand",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "SDK for browser agents \u2014 structured ways to build reliable browser automation agents.",
    exampleIntro: "You\u2019re building browser agents and want an SDK, not only scripts.",
    steps: ["Install Stagehand.", "Write a small browser flow on staging.", "Add assertions; integrate with your agent loop."],
    prompts: ["Automate a staging checkout with Stagehand.", "Stagehand vs Playwright raw vs browser-use?", "Flake-reduction tips."] as Spec["prompts"],
    prerequisites: ["Node/Python per docs", "Staging URLs"],
    tips: ["Prefer stable selectors/roles.", "APIs > browsers when possible."],
    stars: "24k",
    group: "browser-research",
  },
  {
    repo: "bytedance/UI-TARS",
    name: "UI-TARS",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Native GUI interaction agents \u2014 models/stack for agents that use interfaces directly.",
    exampleIntro: "You\u2019re researching or building agents that operate GUIs natively.",
    steps: ["Read UI-TARS docs/models.", "Try a supported environment.", "Benchmark on staging tasks before productizing."],
    prompts: ["Explain UI-TARS vs traditional RPA.", "What tasks fit GUI agents?", "Eval harness ideas for GUI agents."] as Spec["prompts"],
    prerequisites: ["Compatible runtime/hardware", "Staging only"],
    tips: ["Research-heavy \u2014 validate reliability.", "Human override required."],
    stars: "11k",
    group: "browser-research",
  },
  {
    repo: "vitali87/code-graph-rag",
    name: "Code Graph RAG",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Graph-RAG agent for codebases \u2014 retrieve via code graphs, not only chunk search.",
    exampleIntro: "Repo RAG feels dumb; you want graph-aware code retrieval for agents.",
    steps: ["Clone code-graph-rag.", "Index a medium repo.", "Ask architecture questions; compare to plain vector RAG."],
    prompts: ["Index our service with code-graph-rag and ask for auth flow.", "When does graph RAG beat chunk RAG?", "Keep the index fresh in CI?"] as Spec["prompts"],
    prerequisites: ["Repo access", "Compute for indexing"],
    tips: ["Reindex on main merges.", "Start with one service."],
    stars: "3.2k",
    group: "browser-research",
  },
  {
    repo: "Graphify-Labs/graphify",
    name: "Graphify",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Turn code/docs into a knowledge graph agents can use.",
    exampleIntro: "Your agents need structured knowledge graphs from code and docs, not only embeddings.",
    steps: ["Install Graphify.", "Ingest a docs+code sample.", "Query the graph from an agent tool."],
    prompts: ["Graphify our docs into a knowledge graph.", "Graphify vs plain LlamaIndex RAG?", "What relationships matter for support agents?"] as Spec["prompts"],
    prerequisites: ["Corpus to ingest", "Hosting"],
    tips: ["Garbage in \u2192 garbage graph.", "Define entity types up front."],
    stars: "105k",
    group: "memory-infra",
  },
  {
    repo: "punkpeye/awesome-mcp-servers",
    name: "Awesome MCP Servers",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Curated collection of MCP servers agents can plug into.",
    exampleIntro: "You don\u2019t know which MCP servers exist for the tools you care about.",
    steps: ["Browse the awesome list.", "Pick 1\u20132 servers.", "Add them to your MCP client; test read-only first."],
    prompts: ["Find MCP servers for GitHub + Slack from the awesome list.", "How do we vet an MCP server\u2019s security?", "Shortlist for a SaaS ops agent."] as Spec["prompts"],
    prerequisites: ["MCP-compatible client"],
    tips: ["MCP servers are code execution surfaces \u2014 audit them.", "Prefer official servers when available."],
    stars: "92k",
    group: "memory-infra",
  },
  {
    repo: "modelcontextprotocol/servers",
    name: "Official MCP Servers",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Official Model Context Protocol servers reference implementations.",
    exampleIntro: "You want canonical MCP servers, not only community lists.",
    steps: ["Clone modelcontextprotocol/servers.", "Run a reference server (filesystem/git etc.) in a sandbox.", "Connect from Claude/Cursor MCP config."],
    prompts: ["Run the official filesystem MCP server in a sandbox folder.", "Which official servers should we enable for eng?", "MCP threat model basics."] as Spec["prompts"],
    prerequisites: ["MCP client", "Sandbox directories"],
    tips: ["Constrain filesystem roots.", "Official \u2260 enable-all."],
    stars: "89k",
    group: "memory-infra",
  },
  {
    repo: "daytonaio/daytona",
    name: "Daytona",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Secure infrastructure for running AI-generated code in isolated environments.",
    exampleIntro: "Coding agents need somewhere safe to run code they generate.",
    steps: ["Deploy/use Daytona per docs.", "Connect your coding agent to Daytona workspaces.", "Run agent code only inside those workspaces."],
    prompts: ["Set up Daytona for our coding agents\u2019 execution.", "Daytona vs E2B sandboxes?", "Network egress policies we should set."] as Spec["prompts"],
    prerequisites: ["Cloud/account", "Agent integration"],
    tips: ["Never run agent code on developer laptops by default.", "Lock egress."],
    stars: "72k",
    group: "memory-infra",
  },
  {
    repo: "mem0ai/mem0",
    name: "Mem0",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Universal memory layer for AI agents \u2014 persist what matters across sessions.",
    exampleIntro: "Your agents forget everything between chats and re-ask the same questions.",
    steps: ["Install Mem0.", "Attach memory to one agent.", "Define what is stored vs ignored (PII policy)."],
    prompts: ["Add Mem0 memory to our support agent.", "Mem0 vs Letta memory?", "PII rules for agent memory."] as Spec["prompts"],
    prerequisites: ["Store/backend", "Privacy policy"],
    tips: ["Memory without governance becomes a liability.", "Expire stale memories."],
    stars: "63k",
    group: "memory-infra",
  },
  {
    repo: "BerriAI/litellm",
    name: "LiteLLM",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "AI gateway / multi-LLM router \u2014 one interface to many model providers.",
    exampleIntro: "You\u2019re tired of rewriting clients for every model vendor.",
    steps: ["Deploy LiteLLM proxy.", "Point apps at the proxy.", "Add budgets, logging, and fallbacks."],
    prompts: ["Deploy LiteLLM with OpenAI+Anthropic fallbacks.", "LiteLLM vs Portkey?", "Budget alerts setup."] as Spec["prompts"],
    prerequisites: ["Hosting", "Provider keys"],
    tips: ["Central gateway = central cost control.", "Log prompts carefully (PII)."],
    stars: "56k",
    group: "memory-infra",
  },
  {
    repo: "run-llama/llama_index",
    name: "LlamaIndex",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Document agents + RAG platform for building context-augmented LLM apps.",
    exampleIntro: "You need serious document RAG/agents over company knowledge.",
    steps: ["Install LlamaIndex.", "Ingest a doc set.", "Build a query engine; then try an agent over tools+docs."],
    prompts: ["Build LlamaIndex RAG over our Notion export.", "LlamaIndex vs Haystack?", "Agent vs query-engine when to choose."] as Spec["prompts"],
    prerequisites: ["Python", "Documents"],
    tips: ["Chunking and metadata quality dominate.", "Eval questions before agents."],
    stars: "52k",
    group: "memory-infra",
  },
  {
    repo: "stanfordnlp/dspy",
    name: "DSPy",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Program agents with optimized prompts/pipelines \u2014 don\u2019t only hand-write prompts.",
    exampleIntro: "Prompt spaghetti isn\u2019t scaling; you want programmed, optimizable LLM pipelines.",
    steps: ["Install DSPy.", "Define a signature/module.", "Optimize on a small dataset of examples."],
    prompts: ["Rewrite our FAQ bot as a DSPy module.", "DSPy vs raw LangChain prompts?", "How does optimization work intuitively?"] as Spec["prompts"],
    prerequisites: ["Python", "Labeled examples help"],
    tips: ["Examples beat vibes.", "Keep a held-out eval set."],
    stars: "37k",
    group: "memory-infra",
  },
  {
    repo: "langfuse/langfuse",
    name: "Langfuse",
    type: "skill",
    categories: ["engineering", "operations", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Agent/LLM observability and evals \u2014 traces, scores, and prompt management.",
    exampleIntro: "You can\u2019t improve agents you can\u2019t see.",
    steps: ["Deploy Langfuse.", "Instrument one agent path.", "Review traces weekly; add scores."],
    prompts: ["Add Langfuse tracing to our support agent.", "Langfuse vs AgentOps?", "What should we score first?"] as Spec["prompts"],
    prerequisites: ["Hosting/cloud", "SDK install"],
    tips: ["Observability before more tools.", "Sample if volume is huge."],
    stars: "33k",
    group: "memory-infra",
  },
  {
    repo: "sgl-project/sglang",
    name: "SGLang",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Fast serving runtime for LLMs \u2014 backend speed for agent workloads.",
    exampleIntro: "Agent latency/cost is dominated by serving; you need a fast runtime.",
    steps: ["Deploy SGLang with a supported model.", "Point agents at the OpenAI-compatible endpoint.", "Load-test realistic agent prompt shapes."],
    prompts: ["Serve a 7B model with SGLang for our agents.", "SGLang vs vLLM?", "Caching tips for agent workloads."] as Spec["prompts"],
    prerequisites: ["GPU server", "Model license"],
    tips: ["Match serving stack to traffic pattern.", "Auth in front."],
    stars: "32k",
    group: "memory-infra",
  },
  {
    repo: "lyogavin/airllm",
    name: "AirLLM",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    what: "Run huge LLMs on tiny GPUs via layer-wise inference.",
    exampleIntro: "You want to experiment with large models on consumer GPUs.",
    steps: ["Install AirLLM.", "Start with a smaller model than 70B.", "Run a short generation; expect slower speed."],
    prompts: ["Run AirLLM with a mid-size model on 8GB VRAM.", "AirLLM vs quantized GGUF via llama.cpp?", "When is cloud rental smarter?"] as Spec["prompts"],
    prerequisites: ["NVIDIA GPU", "Disk for weights"],
    tips: ["Slow but possible \u2014 set expectations.", "Don\u2019t call it production serving."],
    stars: "30k",
    group: "memory-infra",
  },
  {
    repo: "ComposioHQ/composio",
    name: "Composio",
    type: "agent",
    categories: ["engineering", "operations", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    what: "1000+ tools and auth integrations so agents can act in real apps.",
    exampleIntro: "Your agent can think but can\u2019t reliably take actions in Gmail/Jira/etc.",
    steps: ["Install Composio.", "Connect one app with least scopes.", "Call it from your agent; require confirmation on writes."],
    prompts: ["Connect GitHub read-only via Composio to our agent.", "Composio vs Zapier MCP?", "Write-action approval patterns."] as Spec["prompts"],
    prerequisites: ["OAuth apps", "Agent framework"],
    tips: ["Read-only first.", "Scope OAuth tightly."],
    stars: "30k",
    group: "memory-infra",
  },
  {
    repo: "letta-ai/letta",
    name: "Letta",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Stateful agents with advanced memory (formerly MemGPT-lineage ideas).",
    exampleIntro: "You need agents that manage long-term memory deliberately, not just a chat log.",
    steps: ["Install Letta.", "Create a stateful agent.", "Define memory rules; test across sessions."],
    prompts: ["Create a Letta agent that remembers project preferences.", "Letta vs Mem0?", "Memory hierarchical design tips."] as Spec["prompts"],
    prerequisites: ["Runtime/hosting", "Privacy rules"],
    tips: ["Stateful \u2260 immortal \u2014 plan deletions.", "Test multi-session explicitly."],
    stars: "24k",
    group: "memory-infra",
  },
  {
    repo: "modelcontextprotocol/python-sdk",
    name: "MCP Python SDK",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Official Python SDK for building Model Context Protocol servers and clients.",
    exampleIntro: "You\u2019re implementing custom MCP servers in Python.",
    steps: ["Install the MCP Python SDK.", "Scaffold a minimal server.", "Connect from an MCP client; test tools in sandbox."],
    prompts: ["Scaffold an MCP server that exposes our internal search API.", "MCP Python SDK quickstart checklist.", "Auth patterns for MCP tools."] as Spec["prompts"],
    prerequisites: ["Python", "MCP client for testing"],
    tips: ["Treat tools as public API surface.", "Validate inputs hard."],
    stars: "24k",
    group: "memory-infra",
  },
  {
    repo: "e2b-dev/E2B",
    name: "E2B",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Secure sandboxes for agent-generated code execution.",
    exampleIntro: "Agents write code that must run somewhere safer than your laptop.",
    steps: ["Create an E2B account/project.", "Run a hello sandbox.", "Point your coding agent\u2019s execute step at E2B."],
    prompts: ["Run Python in an E2B sandbox from our agent.", "E2B vs Daytona?", "Network restrictions we should enable."] as Spec["prompts"],
    prerequisites: ["API access", "Agent integration"],
    tips: ["Default deny network if possible.", "Time-limit sandboxes."],
    stars: "13k",
    group: "memory-infra",
  },
  {
    repo: "Portkey-AI/gateway",
    name: "Portkey Gateway",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "AI gateway with guardrails \u2014 route, observe, and control LLM traffic.",
    exampleIntro: "You need an AI gateway with guardrails for production agent traffic.",
    steps: ["Deploy Portkey gateway.", "Route one app through it.", "Enable logging + basic guardrails."],
    prompts: ["Put our agent traffic behind Portkey.", "Portkey vs LiteLLM?", "Which guardrails first?"] as Spec["prompts"],
    prerequisites: ["Hosting", "Provider keys"],
    tips: ["Gateways are control planes \u2014 own the config.", "Watch PII in logs."],
    stars: "13k",
    group: "memory-infra",
  },
  {
    repo: "AgentOps-AI/agentops",
    name: "AgentOps",
    type: "skill",
    categories: ["engineering", "operations", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Agent monitoring and cost tracking for multi-step agents.",
    exampleIntro: "Agent bills are rising and you can\u2019t see which step costs money.",
    steps: ["Install AgentOps SDK.", "Wrap one agent run.", "Review cost + failure dashboards weekly."],
    prompts: ["Instrument our CrewAI/AutoGen job with AgentOps.", "AgentOps vs Langfuse?", "Cost attribution by tool call."] as Spec["prompts"],
    prerequisites: ["SDK install", "Agent entrypoints"],
    tips: ["If you can\u2019t meter it, you can\u2019t manage it.", "Alert on cost spikes."],
    stars: "5.8k",
    group: "memory-infra",
  },
  {
    repo: "livekit/agents",
    name: "LiveKit Agents",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    what: "Realtime voice AI agents built on LiveKit\u2019s realtime transport.",
    exampleIntro: "You\u2019re building voice agents that need low-latency realtime audio.",
    steps: ["Install livekit-agents.", "Run a voice agent example.", "Connect STT/LLM/TTS; test on a staging room."],
    prompts: ["Build a LiveKit voice agent that answers product FAQs.", "LiveKit Agents architecture simply?", "Latency budget checklist."] as Spec["prompts"],
    prerequisites: ["LiveKit project", "STT/TTS providers"],
    tips: ["Voice is unforgiving on latency.", "Always offer a human handoff."],
    stars: "13k",
    group: "voice-multimodal",
  },
];

export const AI_AGENTS_CATALOG: DirectoryEntry[] = SPECS.map(entryFromSpec);
