import type { DirectoryEntry } from "./types";

/** Seeded from Claude skills roundup articles. Update via chat when new links are shared. */
export const DIRECTORY_ENTRIES: DirectoryEntry[] = [
  {
    slug: "ab-testing",
    name: "A/B Testing Frameworks",
    type: "skill",
    summary: "Marketing Skills sub-skill for planning/designing experiments and growth testing programs—highlighted in the BrowserAct article.",
    categories: ["marketing","growth","product"],
    industries: ["saas","ecommerce","other"],
    link: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/ab-testing",
    installation: "```bash\nnpx skills add coreyhaines31/marketingskills --skill ab-testing\n```",
    howToUse: "State hypothesis, metric, and surface; skill structures the experiment design and implementation plan.",
    useCases: ["Pricing page A/B plan","CTA copy experiment","Onboarding variant test","Experiment backlog for growth"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "accesslint-refactor",
    name: "AccessLint Refactor",
    type: "skill",
    summary: "Multi-file accessibility refactor skill that adds missing alt text, ARIA labels, and semantic HTML while preserving code style.",
    categories: ["engineering","design","product"],
    industries: ["saas","other"],
    link: "https://github.com/accesslint/claude-marketplace",
    installation: "```bash\n/plugin install accesslint@accesslint\n```",
    howToUse: "Point at components/forms and ask to fix accessibility issues across files.",
    useCases: ["Fix missing alt/ARIA in a form","Semantic HTML pass on a page","Multi-file a11y cleanup before audit","Preserve style while adding labels"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "accesslint-reviewer",
    name: "AccessLint Reviewer",
    type: "agent",
    summary: "AccessLint AI reviewer agent that performs multi-step WCAG 2.1 A/AA codebase scans and produces prioritized audit reports with severity and WCAG references.",
    categories: ["design","engineering","product"],
    industries: ["saas","healthtech","education","other"],
    link: "https://github.com/accesslint/claude-marketplace",
    installation: "```bash\n/plugin marketplace add accesslint/claude-marketplace\n/plugin install accesslint@accesslint\n```",
    howToUse: "Ask the accesslint reviewer to scan `src/components/` (or similar) and produce a structured a11y audit report.",
    useCases: ["Full WCAG A/AA code review","Prioritized a11y issue backlog","Pre-release accessibility audit","Navigate multi-file context for systemic issues"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "agent-sandbox",
    name: "Agent Sandbox",
    type: "skill",
    summary: "Community skill (disler) that isolates agent execution in E2B cloud sandboxes so destructive mistakes don’t hit your local filesystem/dev DB.",
    categories: ["engineering","operations","other"],
    industries: ["saas","other"],
    link: "https://github.com/disler/agent-sandbox-skill",
    installation: "```bash\ngit clone https://github.com/disler/agent-sandbox-skill.git ~/.claude/skills/agent-sandbox\n# skill drives: uv run sbx init|exec|kill\n```",
    howToUse: "Ask Claude to run builds/tests/experiments in a sandbox first; promote only the worth-keeping diff back locally.",
    useCases: ["Safe full-stack experiments","Run npm test in isolation","Prevent accidental DB wipes","Forked cloud sandbox before deploy scripts"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "algorithmic-art",
    name: "Algorithmic Art",
    type: "skill",
    summary: "Generates fractal/geometric/math-derived visuals (e.g. p5.js) with parameterized seeds—more distinctive social/creative output than stock imagery.",
    categories: ["design","marketing","other"],
    industries: ["agency","education","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/algorithmic-art\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Describe motifs, seed parameters, and export format; skill produces generative SVG/canvas/p5 compositions.",
    useCases: ["Unique social cover art","Generative poster for an event","Parameterized art demo for a talk","Math-curious visual experiments"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "amazon-competitor-analyzer",
    name: "Amazon Competitor Analyzer",
    type: "skill",
    summary: "BrowserAct skill that extracts Amazon product competitive intel (pricing, ratings, reviews, availability, positioning) via anti-bot browser automation.",
    categories: ["marketing","growth","sales","operations"],
    industries: ["ecommerce","marketplace","other"],
    link: "https://github.com/browser-act/skills",
    installation: "```bash\nnpx skills add https://github.com/browser-act/skills\n# or OpenClaw: paste the skill SKILL.md URL\n```",
    howToUse: "Provide an ASIN or search query; skill scrapes and returns a structured competitive report.",
    useCases: ["Track rival Amazon listings","Find pricing gaps","Surface review trends","On-demand market monitoring for sellers"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "asana-skills",
    name: "Asana Skills for Claude",
    type: "skill",
    summary: "Asana partner skills from Anthropic’s Partner Skills Directory—workflow guidance on top of Asana MCP connectivity.",
    categories: ["operations","product","other"],
    industries: ["saas","agency","other"],
    link: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    installation: "Enable Asana partner skill in Claude skills directory and connect Asana MCP/connector.",
    howToUse: "Describe project/task setup goals; skill orchestrates Asana workflows via the connector.",
    useCases: ["Project setup","Task creation with assignees","Status rollups","Team workload planning"],
    sources: ["https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "atlassian-skills",
    name: "Atlassian Skills for Claude",
    type: "skill",
    summary: "Atlassian partner skills referenced in Claude.ai browse lists and Anthropic’s Partner Skills Directory for Jira/Confluence-style workflows.",
    categories: ["operations","engineering","product"],
    industries: ["saas","other"],
    link: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    installation: "Enable via Claude.ai Customize → Skills → Browse skills (Atlassian partner) and connect Atlassian MCP/connector.",
    howToUse: "Ask for sprint/ticket/docs workflows once Atlassian skill + connector are on.",
    useCases: ["Create Jira tickets from a brief","Sprint planning assistance","Confluence doc updates","Bug triage notes"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "batch",
    name: "Batch",
    type: "skill",
    summary: "Bundled Claude Code skill (`/batch`) for fanning work out across many files in one structured pass.",
    categories: ["engineering","operations","other"],
    industries: ["saas","other"],
    link: "https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f",
    installation: "Bundled with Claude Code; use `/batch` for multi-file fan-out tasks.",
    howToUse: "Describe the repeated edit/check across paths; `/batch` coordinates the fan-out.",
    useCases: ["Rename a pattern across modules","Apply a lint fix set repo-wide","Generate stubs for many files"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "bencium-controlled-ux-designer",
    name: "Bencium Controlled UX Designer",
    type: "skill",
    summary: "Sibling of Innovative UX Designer for consistency-first projects—same deep UX references, tighter control over creative variance.",
    categories: ["design","product","operations"],
    industries: ["saas","fintech","healthtech","other"],
    link: "https://github.com/bencium/bencium-claude-code-design-skill",
    installation: "```bash\ncp -r bencium-claude-code-design-skill/bencium-controlled-ux-designer ~/.claude/skills/\n```",
    howToUse: "Use when design-system consistency matters more than novelty; same activation patterns as the innovative variant.",
    useCases: ["Enterprise settings UI under a strict DS","Regulated-product form patterns","Responsive redesign within brand constraints","Motion specs without visual chaos"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "bencium-innovative-ux-designer",
    name: "Bencium Innovative UX Designer",
    type: "skill",
    summary: "Deep UX reference skill (~28k chars) encouraging bold, distinctive design with shared accessibility, responsive, motion, and design-system templates.",
    categories: ["design","product"],
    industries: ["saas","agency","other"],
    link: "https://github.com/bencium/bencium-claude-code-design-skill",
    installation: "```bash\ngit clone https://github.com/bencium/bencium-claude-code-design-skill.git\ncp -r bencium-claude-code-design-skill/bencium-innovative-ux-designer ~/.claude/skills/\n```",
    howToUse: "Ask for creative UX flows/pages; skill applies innovative UX philosophy plus ACCESSIBILITY/RESPONSIVE/MOTION refs.",
    useCases: ["Bold checkout with recovery patterns","Expressive onboarding wizard","Settings with progressive disclosure","Form UX review with motion specs"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "brand-applicator",
    name: "Brand Applicator",
    type: "skill",
    summary: "Applies fonts, colors, and logos from your brand rules to finished documents so drafts look like real deliverables.",
    categories: ["design","marketing","operations"],
    industries: ["saas","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload from article download; provide brand rules (fonts/colors/logos) as skill assets or context.",
    howToUse: "Hand over a completed doc and brand rules; skill handles last-mile visual branding.",
    useCases: ["Brand a proposal before client send","Apply logo/fonts to a report","Polish a draft one-pager","Standardize deliverable look"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "brand-guidelines",
    name: "Brand Guidelines",
    type: "skill",
    summary: "Encodes palette, logo rules, voice/tone, and typography so slides, docs, and web artifacts stay on-brand without manual last-mile polishing.",
    categories: ["design","marketing","operations"],
    industries: ["saas","agency","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
    installation: "Enable in Claude.ai Skills (Anthropic example) or install from anthropics/skills; customize with your brand tokens.",
    howToUse: "Toggle on and prompt normally (“create a presentation…”) or pair with pptx/docx/frontend-design; Claude applies brand rules automatically.",
    useCases: ["Anthropic-branded demo deck","On-brand marketing one-pager","Consistent colors/fonts across team artifacts","Enterprise brand compliance for AI outputs"],
    sources: ["https://artificialcorner.com/p/claude-skills","https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "branded-carousel-generator",
    name: "Branded Carousel Generator",
    type: "skill",
    summary: "Shapes content into publishable branded social carousels—not generic template splits—so posts can recur without redesigning from scratch.",
    categories: ["marketing","growth","design"],
    industries: ["saas","agency","ecommerce","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload skill from Artificial Corner download links via Customize → Skills.",
    howToUse: "Paste content/ideas and brand cues; skill outputs a carousel structured for social publishing.",
    useCases: ["LinkedIn thought-leadership carousel","Product tip series","Launch announcement carousel","Repurpose a blog into slides"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "canva-skills",
    name: "Canva Skills for Claude",
    type: "skill",
    summary: "Canva partner skills listed in Anthropic’s Partner Skills Directory for design/asset workflows atop Canva connectivity.",
    categories: ["design","marketing","other"],
    industries: ["saas","agency","ecommerce","other"],
    link: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    installation: "Enable Canva partner skill via Partner Skills Directory / Claude skills browse; connect Canva as required.",
    howToUse: "Ask for branded visual assets/workflows that Canva skill + connector can execute.",
    useCases: ["Social creative drafts","Presentation visuals","Brand kit-aligned assets","Marketing collateral variations"],
    sources: ["https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "canvas-design",
    name: "Canvas Design",
    type: "skill",
    summary: "Produces social graphics, event posters, and article covers as PNG/PDF via HTML5 canvas compositions without Photoshop.",
    categories: ["design","marketing","other"],
    industries: ["saas","agency","ecommerce","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/canvas-design\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Describe the asset type, copy, and brand cues; request PNG/PDF output for posts, posters, or covers.",
    useCases: ["LinkedIn/OG article cover","Event poster","Social promo graphic","Campaign visual variations"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "claude-api",
    name: "Claude API",
    type: "skill",
    summary: "Up-to-date reference skill for the Claude API including Managed Agents, multiagent patterns, and webhooks—also exposed as a bundled Claude Code `/claude-api` helper.",
    categories: ["engineering","other"],
    industries: ["saas","other"],
    link: "https://github.com/anthropics/skills",
    installation: "Bundled with Claude Code (`/claude-api`) and available via anthropics/skills example skills; enable alongside other Anthropic example skills.",
    howToUse: "Ask API/integration questions or run `/claude-api` for sub-task queries against Anthropic’s API surface.",
    useCases: ["Look up Managed Agents patterns","Webhook integration guidance","Multiagent API design help","Keep API usage current without outdated training cutoffs"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "claude-seo",
    name: "Claude SEO",
    type: "skill",
    summary: "Comprehensive Claude Code SEO toolkit (article: 12 sub-skills + 6 parallel subagents; repo evolved further) for audits, schema, sitemaps, GEO/AEO, and prioritized recommendations.",
    categories: ["marketing","growth","engineering"],
    industries: ["saas","ecommerce","agency","marketplace","other"],
    link: "https://github.com/AgriciDaniel/claude-seo",
    installation: "```bash\ngit clone --depth 1 https://github.com/AgriciDaniel/claude-seo.git && bash claude-seo/install.sh\n```",
    howToUse: "Submit a URL and run SEO audit commands (e.g. `/seo audit`); parallel subagents synthesize a prioritized action plan.",
    useCases: ["Full-site SEO audit","Schema markup validation","Sitemap generation","AI-search (GEO/AEO) optimization","Page-level prioritized fixes"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "composition-patterns",
    name: "Vercel Composition Patterns",
    type: "skill",
    summary: "Teaches scalable React composition (compound components, context interfaces, explicit variants) to fight boolean-prop proliferation in design systems.",
    categories: ["engineering","design","product"],
    industries: ["saas","other"],
    link: "https://github.com/vercel-labs/agent-skills/tree/main/skills/composition-patterns",
    installation: "```bash\ncp -r vercel-labs/agent-skills/skills/composition-patterns ~/.claude/skills/\n```",
    howToUse: "Ask to refactor components away from boolean props toward compound/variant APIs.",
    useCases: ["Refactor a 15-boolean-prop component","Design a Radix-style Select API","Review a component library for composition anti-patterns","Migrate off forwardRef for React 19"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "contract-reviewer",
    name: "Contract Reviewer",
    type: "skill",
    summary: "Breaks contracts into key terms, red/yellow flags, missing protections, and pushback points—triage attention, not a lawyer replacement.",
    categories: ["operations","sales","other"],
    industries: ["saas","fintech","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload skill; then upload the contract file in chat.",
    howToUse: "Upload a contract and ask for risk-focused review; prioritize red/yellow flags and missing clauses.",
    useCases: ["NDA red-flag pass","Vendor MSA triage before counsel","Highlight missing liability protections","Prep negotiation pushback list"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "contrast-checker",
    name: "AccessLint Contrast Checker",
    type: "skill",
    summary: "Interactive WCAG contrast checker that calculates ratios, AA/AAA compliance, and suggests accessible alternatives that preserve design intent.",
    categories: ["design","engineering","product"],
    industries: ["saas","healthtech","education","other"],
    link: "https://github.com/accesslint/claude-marketplace",
    installation: "```bash\n/plugin marketplace add accesslint/claude-marketplace\n/plugin install accesslint@accesslint\n```",
    howToUse: "Ask for contrast between hex colors or review UI colors for WCAG; uses bundled MCP contrast tools when available.",
    useCases: ["Check #333 on #f5f5f5 for body text","Suggest accessible accent alternatives","Validate AA/AAA for a palette","Pair with theme generation skills"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "cro",
    name: "CRO (Landing Page Conversion)",
    type: "skill",
    summary: "Marketing Skills sub-skill for conversion-rate optimization on homepages, landing pages, and forms—explicitly called out in BrowserAct’s marketing collection summary.",
    categories: ["marketing","growth","product"],
    industries: ["saas","ecommerce","agency","other"],
    link: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/cro",
    installation: "```bash\nnpx skills add coreyhaines31/marketingskills --skill cro\n```",
    howToUse: "Share the page URL/copy/goal; ask to optimize conversions with the cro skill.",
    useCases: ["Homepage conversion teardown","Signup form friction audit","Landing page hypothesis list","CTA/hierarchy recommendations"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "debug",
    name: "Debug",
    type: "skill",
    summary: "Bundled Claude Code sibling skill (`/debug`) oriented around stack traces and debugging workflows.",
    categories: ["engineering","other"],
    industries: ["saas","other"],
    link: "https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f",
    installation: "Bundled with Claude Code; invoke `/debug` when troubleshooting.",
    howToUse: "Paste a stack trace or failing behavior and run `/debug` for structured diagnosis.",
    useCases: ["Trace a production exception","Local test failure diagnosis","Narrow a flaky bug"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "decision-council",
    name: "Decision Council",
    type: "skill",
    summary: "Runs multiple expert personas in parallel, then synthesizes a recommendation with next steps—structured clash of viewpoints before the answer.",
    categories: ["product","operations","other"],
    industries: ["saas","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload from Artificial Corner guide/download; enable in Skills.",
    howToUse: "State the decision and constraints; skill simulates multi-persona debate then a synthesized recommendation.",
    useCases: ["Pricing change go/no-go","Build vs buy architecture call","Hiring plan tradeoffs","Launch timing decision"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "doc-coauthoring",
    name: "Document Co-Authoring",
    type: "skill",
    summary: "Collaborative multi-pass writing with human judgment each stage and diff-style suggestions—better than full AI authorship for strategy docs and proposals.",
    categories: ["product","operations","other"],
    industries: ["saas","agency","education","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Write a section, ask Claude to respond/revise with the skill; iterate section-by-section; export via docx when ready.",
    useCases: ["Team strategy document","Client proposal with human checkpoints","Multi-pass editing with suggested diffs","Policy doc collaboration"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "document-skills",
    name: "Document Skills (Plugin Bundle)",
    type: "skill",
    summary: "Anthropic Plugin Set that installs PDF, DOCX, PPTX, and XLSX together so document workflows chain without separate MCP servers for each format.",
    categories: ["operations","engineering","other"],
    industries: ["saas","other"],
    link: "https://github.com/anthropics/skills",
    installation: "```bash\n/plugin marketplace add anthropics/skills\n/plugin install document-skills@anthropic-agent-skills\n```",
    howToUse: "Ask for any office artifact (.pdf/.docx/.pptx/.xlsx); Claude loads the matching document skill from the bundle.",
    useCases: ["One-prompt CSV → Excel → board deck","Replace multiple document MCP servers","Standardize office output across a team"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a"],
  },
  {
    slug: "docx",
    name: "DOCX / Word Documents",
    type: "skill",
    summary: "Creates and edits genuine `.docx` files with styles, tracked changes, comments, and template preservation—not Markdown pretending to be Word.",
    categories: ["operations","product","other"],
    industries: ["saas","agency","education","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/docx",
    installation: "```bash\n/plugin install document-skills@anthropic-agent-skills\n# or copy skills/docx into ~/.claude/skills/\n```",
    howToUse: "Request a formatted Word report, proposal, or revision-marked draft; pairs with doc-coauthoring for multi-pass editing.",
    useCases: ["Generate a weekly status report as .docx","Apply tracked changes to a policy doc","Create a client proposal from notes","Preserve template styles while rewriting sections"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "emails",
    name: "Email Sequences",
    type: "skill",
    summary: "Marketing Skills sub-skill for email sequences, drips, and lifecycle flows—named among the collection’s highlighted capabilities.",
    categories: ["marketing","growth","sales"],
    industries: ["saas","ecommerce","agency","other"],
    link: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/emails",
    installation: "```bash\nnpx skills add coreyhaines31/marketingskills --skill emails\n```",
    howToUse: "Describe audience, offer, and sequence goal; skill drafts/optimizes the email flow.",
    useCases: ["Trial onboarding drip","Abandoned cart sequence","Launch email series","Nurture cadence for PQLs"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "explainer-graphic",
    name: "Explainer Graphic",
    type: "skill",
    summary: "Converts hard-to-explain concepts into HTML explainers with analogies, visual steps, and short scannable sections.",
    categories: ["marketing","product","other"],
    industries: ["saas","education","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload via Claude.ai Skills from the article’s download link (zip/SKILL.md).",
    howToUse: "Provide a concept that isn’t sticking in prose; skill returns an HTML visual walkthrough.",
    useCases: ["Explain a product architecture to sales","Visual onboarding for a feature","Turn a dense blog section into steps","Teaching aid for a technical concept"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "figma-skills",
    name: "Figma Skills for Claude",
    type: "skill",
    summary: "Figma partner skills for Claude (alongside Implement Design / Figma MCP)—listed in Snyk and Anthropic partner directories for design-to-dev workflows.",
    categories: ["design","engineering","product"],
    industries: ["saas","agency","other"],
    link: "https://github.com/figma/mcp-server-guide",
    installation: "Install Figma Claude plugin/MCP (`figma@claude-plugins-official` or MCP server guide); enable Figma partner skills where available.",
    howToUse: "Authenticate Figma, then ask for design inspection, handoff, or implementation tasks.",
    useCases: ["Design-to-code handoff","Inspect components/tokens","Implement selected frames","Keep design context in coding sessions"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf","https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "frontend-design",
    name: "Frontend Design",
    type: "skill",
    summary: "Anthropic’s anti–AI-slop UI skill: forces distinctive typography, color, motion, spatial composition, and backgrounds before coding so interfaces don’t default to generic purple/Inter templates.",
    categories: ["design","engineering","product"],
    industries: ["saas","agency","marketplace","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    installation: "```bash\ngit clone https://github.com/anthropics/skills.git\ncp -r skills/skills/frontend-design ~/.claude/skills/\n# or: /plugin marketplace add anthropics/claude-code → frontend-design\n```",
    howToUse: "Ask Claude to build pages/components with an aesthetic direction (e.g. “dark editorial fintech landing page”); skill activates on web UI tasks.",
    useCases: ["Fintech landing page with editorial tone","Health-app dashboard with warm aesthetic","Brutalist portfolio site","Marketing site that avoids AI-default fonts"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/","https://artificialcorner.com/p/claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf","https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "google-news-api",
    name: "Google News API Skill",
    type: "skill",
    summary: "BrowserAct skill for real-time Google News scraping/monitoring without CAPTCHA blocks—structured feeds as a replacement for brittle RSS/API quotas.",
    categories: ["marketing","growth","operations","other"],
    industries: ["saas","agency","other"],
    link: "https://github.com/browser-act/skills",
    installation: "```text\n@openclaw help me install this skill: https://github.com/browser-act/skills/blob/main/google-news-api-skill/SKILL.md\n```\nOr `npx skills add` / clone into `~/.claude/skills/`.",
    howToUse: "Give a keyword/topic; skill returns a structured current-coverage feed for competitive/industry monitoring.",
    useCases: ["Daily market coverage brief","Track brand mentions in news","Content strategy topic monitoring","Pair with Amazon analyzer for intel pipelines"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "implement-design",
    name: "Implement Design (Figma)",
    type: "skill",
    summary: "Public Figma skill/workflow for translating designs into production-ready code with tighter visual fidelity via Figma MCP (design context, screenshots, assets).",
    categories: ["design","engineering","product"],
    industries: ["saas","agency","other"],
    link: "https://developers.figma.com/docs/figma-mcp-server/skill-figma-implement-design/",
    installation: "Install Figma MCP + skill (e.g. `claude plugin install figma@claude-plugins-official` or from github.com/figma/mcp-server-guide). Authenticate Figma.",
    howToUse: "Paste a Figma URL with `node-id` (or select in desktop MCP) and ask to implement the design in your stack with visual parity.",
    useCases: ["Implement a Figma frame as React+Tailwind","Match design-system tokens from Figma","Close spacing/component drift from mockups","Generate components from Dev Mode nodes"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "internal-comms",
    name: "Internal Comms",
    type: "skill",
    summary: "Templates and tone guidance for announcements, status updates, incident comms, and exec summaries so Slack/email writing matches org voice.",
    categories: ["operations","product","other"],
    industries: ["saas","agency","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/internal-comms\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Describe the audience and message type (incident, launch, status); skill shapes concise, org-appropriate drafts.",
    useCases: ["Incident status update for Slack","Exec weekly summary","Launch announcement","Postmortem-friendly status note"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a"],
  },
  {
    slug: "link-purpose",
    name: "AccessLint Link Purpose",
    type: "skill",
    summary: "Checks link text for descriptiveness and context so users (and screen readers) understand destination without surrounding guesswork.",
    categories: ["design","engineering","product"],
    industries: ["saas","education","other"],
    link: "https://github.com/accesslint/claude-marketplace",
    installation: "```bash\n/plugin install accesslint@accesslint\n```",
    howToUse: "Ask to review link text in a page/component for vague “click here” / unclear purpose patterns.",
    useCases: ["Replace vague CTA link text","Audit nav/link lists for context","Prep content for WCAG link-purpose rules"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "loop",
    name: "Loop",
    type: "skill",
    summary: "Bundled Claude Code skill (`/loop`) for run-until-condition agentic iteration.",
    categories: ["engineering","other"],
    industries: ["saas","other"],
    link: "https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f",
    installation: "Bundled with Claude Code; invoke `/loop` with a clear stop condition.",
    howToUse: "Specify the task and success condition; skill iterates until the condition is met.",
    useCases: ["Fix until tests pass","Iterate a refactor to a green build","Retry flaky setup until stable"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "market-competitors",
    name: "Market Competitors",
    type: "skill",
    summary: "Turns a website or market input into a structured competitive intelligence report usable for positioning decisions—not scattered notes.",
    categories: ["marketing","product","sales","growth"],
    industries: ["saas","ecommerce","marketplace","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload from Artificial Corner download link; optionally pair with browsing/MCP tools for live research.",
    howToUse: "Provide a competitor URL or market; skill returns a formatted competitive intelligence deliverable.",
    useCases: ["Positioning report for a SaaS rival","Market landscape for a new feature","Sales battlecard raw material","Founder competitive brief"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "marketing-skills",
    name: "Marketing Skills (Corey Haines Collection)",
    type: "skill",
    summary: "Comprehensive marketing toolkit collection (CRO, copywriting, SEO, analytics, growth) with 20–49 installable skills—including landing-page CRO, email sequences, A/B testing, and programmatic SEO.",
    categories: ["marketing","growth","sales","product"],
    industries: ["saas","ecommerce","agency","marketplace","other"],
    link: "https://github.com/coreyhaines31/marketingskills",
    installation: "```bash\nnpx skills add coreyhaines31/marketingskills -a claude-code\n# or: /plugin marketplace add coreyhaines31/marketingskills && /plugin install marketing-skills\n```",
    howToUse: "Describe the marketing task; collection routes to skills like cro, emails, ab-testing, programmatic-seo after reading product-marketing context.",
    useCases: ["Landing page CRO audit","Lifecycle email sequence","A/B test design","Programmatic SEO page plan","Full-funnel growth workflow"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "mcp-builder",
    name: "MCP Builder",
    type: "skill",
    summary: "Generates Model Context Protocol servers from a plain-English description so Skills (workflow knowledge) can pair with purpose-built external tools instead of bloated generic MCP packs.",
    categories: ["engineering","operations","other"],
    industries: ["saas","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
    installation: "```bash\n/plugin install mcp-builder@anthropic-agent-skills\n```",
    howToUse: "Describe tools/auth needs (e.g. list_invoices, OAuth from .env); let mcp-builder scaffold the server boilerplate.",
    useCases: ["Internal billing API MCP","Tiny purpose-built MCP instead of a mega registry pack","Bootstrap OAuth tool wiring"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "notebooklm-skill",
    name: "NotebookLM Integration",
    type: "skill",
    summary: "Bridges Claude Code/agents to Google NotebookLM for upload, source-grounded querying, and export of summaries, mind maps, flashcards, and research notes.",
    categories: ["operations","product","other"],
    industries: ["saas","education","healthtech","other"],
    link: "https://github.com/PleasePrompto/notebooklm-skill",
    installation: "```bash\nnpx skills add https://github.com/PleasePrompto/notebooklm-skill --skill notebooklm\n# or clone into ~/.claude/skills/ (Claude Code local; needs network/browser)\n```",
    howToUse: "Connect/auth NotebookLM, point at notebooks/docs, ask for summaries, mind maps, flashcards, or comparative notes.",
    useCases: ["30-page paper → summary + mind map + flashcards","Source-grounded Q&A over internal docs","Research note export","Study deck from uploaded PDFs"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "notion-skills",
    name: "Notion Skills for Claude",
    type: "skill",
    summary: "Partner skill pack treating Notion as a first-class workspace (not just an API)—highlighted as a top partner skill in DEV.to and listed among Claude.ai partner skills.",
    categories: ["operations","product","other"],
    industries: ["saas","agency","education","other"],
    link: "https://www.notion.so",
    installation: "In Claude.ai: Customize → Skills → Browse skills → enable Notion partner skills (with Notion connector/MCP as required).",
    howToUse: "Ask Claude to create/query/update Notion pages, databases, and workflows once the skill + connector are enabled.",
    useCases: ["Set up a project workspace","Status database updates","Meeting notes → Notion pages","Team wiki scaffolding"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "obsidian-skills",
    name: "Obsidian Skills",
    type: "skill",
    summary: "Collection by Obsidian’s CEO enabling native vault work—structured Markdown, Bases, JSON Canvas, auto-tagging, linking, and summaries.",
    categories: ["operations","product","other"],
    industries: ["saas","education","agency","other"],
    link: "https://github.com/kepano/obsidian-skills",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/kepano/obsidian-skills\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Point Claude at your vault workflows; skill creates properly structured notes/canvas and maintains links/tags.",
    useCases: ["Auto-tag and link research notes","Generate JSON Canvas maps","Summarize a vault section","Bootstrap Bases structures"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "openclaw-official-skills",
    name: "OpenClaw Official Skills Collection",
    type: "skill",
    summary: "53 production-tested bundled OpenClaw skills spanning Obsidian notes, Google Workspace (gog), GitHub, Slack, smart home, CI/CD monitoring, social, and more—reference implementations for skill architecture.",
    categories: ["operations","engineering","marketing","other"],
    industries: ["saas","agency","other"],
    link: "https://github.com/openclaw/openclaw",
    installation: "Install/use via OpenClaw (natural language skill URL install or ClawHub CLI). Study bundled skills as templates before building your own.",
    howToUse: "In OpenClaw, paste skill URLs or `clawhub install <slug>`; invoke by describing daily workflows the bundle covers.",
    useCases: ["Obsidian note workflows","Gmail/calendar via gog bridge","GitHub repo management","Slack messaging automation","CI/CD monitoring"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "pdf",
    name: "PDF",
    type: "skill",
    summary: "Official Anthropic document skill for reliable PDF extraction, form filling, table parsing, merging/splitting, and annotation via deterministic scripts rather than hallucinated contents.",
    categories: ["operations","engineering","other"],
    industries: ["saas","fintech","healthtech","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/pdf",
    installation: "```bash\n/plugin marketplace add anthropics/skills\n/plugin install document-skills@anthropic-agent-skills\n# or: npx skills add https://github.com/anthropics/skills/tree/main/skills/pdf\n```",
    howToUse: "Ask Claude to extract fields, fill forms, redact, merge, or summarize PDFs; progressive disclosure loads `forms.md` only when filling forms.",
    useCases: ["Extract NDA form fields from a contract PDF","Batch-fill PDF forms from CSV data","Flag risky clauses in a 48-page agreement","Merge quarterly report PDFs","Parse tables from financial statements"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "pptx",
    name: "PPTX / PowerPoint Presentations",
    type: "skill",
    summary: "Generates real `.pptx` slide decks with layouts, charts, and speaker notes from natural-language briefs—eliminating the blank-deck first draft bottleneck.",
    categories: ["marketing","sales","product","other"],
    industries: ["saas","agency","education","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/pptx",
    installation: "```bash\n/plugin install document-skills@anthropic-agent-skills\n```",
    howToUse: "Describe the audience, narrative, and desired slide count; optionally pair with xlsx for data-backed decks or brand-guidelines for styling.",
    useCases: ["Board-ready deck from a CSV + brief","Sales pitch deck from product notes","Internal QBR with speaker notes","Training deck from a source PDF"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf","https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "programmatic-seo",
    name: "Programmatic SEO",
    type: "skill",
    summary: "Marketing Skills sub-skill for template/data-driven SEO pages at scale—explicitly listed in BrowserAct’s marketing skills highlights.",
    categories: ["marketing","growth","engineering"],
    industries: ["saas","marketplace","ecommerce","other"],
    link: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/programmatic-seo",
    installation: "```bash\nnpx skills add coreyhaines31/marketingskills --skill programmatic-seo\n```",
    howToUse: "Describe the entity/data model and indexation goals; skill plans programmatic page templates and SEO guardrails.",
    useCases: ["City/service page system","Integration directory pages","Comparison page templates","Scaled landing architecture"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "quick-research",
    name: "Quick Research",
    type: "skill",
    summary: "Compresses a topic into a structured brief (summary, features, requirements, pros/cons, pricing, bottom line) instead of a pile of open tabs.",
    categories: ["product","marketing","operations","other"],
    industries: ["saas","education","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload from Artificial Corner download link.",
    howToUse: "Give a topic or release; skill returns an organized research brief.",
    useCases: ["Brief a Claude Cowork release","Competitor feature snapshot","Vendor evaluation one-pager","Market topic bottom-line memo"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "react-best-practices",
    name: "Vercel React Best Practices",
    type: "skill",
    summary: "57 React/Next.js performance rules across 8 impact-ordered categories (waterfalls, bundle size, SSR, fetching, re-renders, etc.) with incorrect/correct examples.",
    categories: ["engineering","product"],
    industries: ["saas","marketplace","other"],
    link: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices",
    installation: "```bash\ngit clone https://github.com/vercel-labs/agent-skills.git\ncp -r agent-skills/skills/react-best-practices ~/.claude/skills/\n```",
    howToUse: "Ask to review/refactor React or Next.js for performance; skill prioritizes waterfalls and bundle size over premature memoization.",
    useCases: ["Eliminate data-fetching waterfalls","Cut barrel-import bundle bloat","Fix unnecessary re-renders","Optimize a slow Next.js page"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "react-native-skills",
    name: "Vercel React Native Skills",
    type: "skill",
    summary: "Mobile UI performance and pattern rules for React Native/Expo: FlashList, GPU-safe animations, navigation, Pressable/expo-image, safe areas, and more.",
    categories: ["engineering","design","product"],
    industries: ["saas","marketplace","healthtech","other"],
    link: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-native-skills",
    installation: "```bash\ncp -r vercel-labs/agent-skills/skills/react-native-skills ~/.claude/skills/\n```",
    howToUse: "Ask why a FlatList janks, request animation/navigation reviews, or optimize Expo UI patterns.",
    useCases: ["Fix slow FlatList scrolling","GPU-accelerate page transitions","Adopt FlashList + memoized items","Review Expo app performance"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "sentry-code-review",
    name: "Sentry Code Review",
    type: "skill",
    summary: "Sentry partner skill that analyzes/fixes bugs in GitHub PRs using Sentry error-monitoring data via Sentry’s MCP—canonical Skills+MCP enhancement example in Anthropic’s guide.",
    categories: ["engineering","operations","other"],
    industries: ["saas","other"],
    link: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    installation: "Connect Sentry MCP, then install the Sentry partner skill from Anthropic’s Partner Skills Directory / Sentry docs; enable alongside the connector.",
    howToUse: "On a PR with related Sentry issues, ask Claude to run Sentry-informed code review and propose fixes.",
    useCases: ["PR review grounded in production errors","Map stack traces to failing code","Prioritize fixes by real user impact"],
    sources: ["https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "simplify",
    name: "Simplify",
    type: "skill",
    summary: "Bundled Claude Code skill (`/simplify`) that rereads the current diff and rewrites it to be cleaner and more maintainable before commit.",
    categories: ["engineering","other"],
    industries: ["saas","other"],
    link: "https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f",
    installation: "Already bundled with Claude Code—no install. Type `/simplify` after a large generated diff.",
    howToUse: "```text\n/simplify\n```\nRun before commits to force complexity reduction on AI-generated code.",
    useCases: ["Clean a large agent diff","Remove redundant abstractions","Pre-commit maintainability pass"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "skill-creator",
    name: "Skill Creator",
    type: "skill",
    summary: "Official meta-skill that scaffolds new skills: YAML frontmatter, trigger-quality descriptions, bundled file structure, review of overlapping/weak triggers, and iterative improvement.",
    categories: ["engineering","product","operations","other"],
    industries: ["saas","agency","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    installation: "Built into Claude.ai Skills; for Claude Code:\n```bash\ncp -r anthropics/skills/skills/skill-creator ~/.claude/skills/\n# or enable skill-creator in Claude.ai Preferences → Skills\n```",
    howToUse: "Say “Use skill-creator to help me build a skill for [workflow]”; answer clarifying questions about audience, triggers, and output format.",
    useCases: ["Scaffold a repo-specific PR review skill","Merge overlapping git helper skills","Improve a vague skill description","Generate test cases for triggering"],
    sources: ["https://artificialcorner.com/p/claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf","https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "slack-gif-creator",
    name: "Slack GIF Creator",
    type: "skill",
    summary: "Narrow skill that generates short, on-message animated GIFs for Slack reactions—proof that tiny, well-scoped skills still earn installs.",
    categories: ["operations","other"],
    industries: ["saas","agency","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Ask for a GIF matching a reaction/context (ship, celebrate, oops); skill generates a short animation for Slack.",
    useCases: ["Ship celebration reaction GIF","Incident humor de-escalation GIF","Team morale / standup reaction clips"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a"],
  },
  {
    slug: "slide-deck-builder",
    name: "Slide Deck Builder",
    type: "skill",
    summary: "Turns a rough idea or source doc into a structured, styled first-draft slide sequence—skipping blank-slide structure work.",
    categories: ["marketing","sales","product","other"],
    industries: ["saas","agency","education","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Per Artificial Corner: Customize → Skills → Upload skill `.zip`/`SKILL.md` (or Personal plugins if multi-skill zip). See article download links.",
    howToUse: "Give a few sentences or a topic; skill returns a coherent slide sequence with applied visual style as a first draft.",
    useCases: ["Pitch deck from a one-paragraph brief","Workshop slides from notes","Internal all-hands outline","Convert a doc into a first-draft deck"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "static-analysis",
    name: "Static Analysis (Trail of Bits)",
    type: "skill",
    summary: "Trail of Bits security skill wrapping Semgrep/CodeQL-style static analysis to catch grep-able vulnerabilities and feed vulnerable blocks back for fixes (`/security-review`).",
    categories: ["engineering","other"],
    industries: ["saas","fintech","healthtech","other"],
    link: "https://github.com/trailofbits/skills",
    installation: "```bash\n/plugin marketplace add trailofbits/skills\n/plugin install static-analysis@trailofbits\n# or cp plugins/static-analysis → ~/.claude/skills/\n```",
    howToUse: "Run `/security-review` before opening a PR; skill flags SQLi, secrets, unsafe deserialization, missing authz patterns, etc.",
    useCases: ["Pre-PR security review","Find hard-coded secrets","Flag SQL injection patterns","Catch missing authorization checks"],
    sources: ["https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "superpowers",
    name: "Superpowers",
    type: "skill",
    summary: "obra/superpowers methodology pack (20+ skills) adding a senior-consultant requirements/planning phase—interrogation, edge cases, TDD, debugging, and collaboration—before execution.",
    categories: ["engineering","product","other"],
    industries: ["saas","other"],
    link: "https://github.com/obra/superpowers",
    installation: "```bash\n/plugin marketplace add obra/superpowers-marketplace\n/plugin install superpowers@superpowers-marketplace\n```",
    howToUse: "Start complex work with Superpowers planning/brainstorming skills before coding; follow TDD/debug/collaboration skills through delivery.",
    useCases: ["Requirements workshop before a feature","TDD-driven implementation","Subagent-driven development with reviews","Structured debugging sessions"],
    sources: ["https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "theme-factory",
    name: "Theme Factory",
    type: "skill",
    summary: "Generates cohesive themes (light/dark, semantic tokens, component variants) as structured JSON/CSS/Tailwind configs to kill early-stage aesthetic decision paralysis.",
    categories: ["design","engineering","product"],
    industries: ["saas","ecommerce","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
    installation: "```bash\n/plugin install theme-factory@anthropic-agent-skills\n# or cp anthropics/skills/skills/theme-factory → ~/.claude/skills/\n```",
    howToUse: "Ask for multiple theme options or CSS variables for a chosen direction; compose with frontend-design for implementation.",
    useCases: ["Batch-generate SaaS UI skins","Produce Tailwind token set for a redesign","Explore light/dark variants before coding","Hand designers structured theme JSON"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "ui-ux-pro-max",
    name: "UI/UX Pro Max",
    type: "skill",
    summary: "Design-intelligence skill with a searchable DB (50+ styles, 97 palettes, font pairings, UX guidelines, chart types, 9 stacks) via a Python CLI and optional persistent MASTER design system.",
    categories: ["design","product","engineering"],
    industries: ["saas","ecommerce","fintech","healthtech","agency","other"],
    link: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
    installation: "```bash\ngit clone https://github.com/nextlevelbuilder/ui-ux-pro-max-skill.git\ncp -r ui-ux-pro-max-skill/.claude/skills/ui-ux-pro-max ~/.claude/skills/\n# or /plugin marketplace add nextlevelbuilder/ui-ux-pro-max-skill\n```",
    howToUse: "Describe product/industry/stack; skill runs design-system search then stack guidelines. Persist with `--design-system --persist` for multi-page apps.",
    useCases: ["Beauty-spa landing design system","SaaS dark-mode dashboard","Fintech trading UI direction","Review components for UX anti-patterns"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "use-of-color",
    name: "AccessLint Use of Color",
    type: "skill",
    summary: "WCAG 1.4.1 checker for meaning conveyed only by color—links, form errors, status indicators, hover/focus affordances.",
    categories: ["design","engineering","product"],
    industries: ["saas","fintech","healthtech","other"],
    link: "https://github.com/accesslint/claude-marketplace",
    installation: "```bash\n/plugin install accesslint@accesslint\n```",
    howToUse: "Ask whether status indicators/errors/links rely solely on color; skill flags and suggests non-color cues.",
    useCases: ["Audit status badges","Find color-only form errors","Check link distinguishability","Hover/focus affordance review"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "web-artifacts-builder",
    name: "Web Artifacts Builder",
    type: "skill",
    summary: "Builds self-contained HTML artifacts—mini-apps, calculators, internal dashboards—from natural language without a full frontend stack.",
    categories: ["engineering","product","operations"],
    industries: ["saas","agency","education","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder",
    installation: "**Claude Code / CLI**\n```bash\nnpx skills add https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder\n# or copy into ~/.claude/skills/<skill-name>/\n```\n\n**Plugin marketplace**\n```text\n/plugin marketplace add <org/repo>\n/plugin install <skill>@<marketplace>\n```\n\n**Claude.ai**\nCustomize → Skills → Upload `.zip` or `SKILL.md` → enable the skill.\n\nAudit `SKILL.md` and any scripts before install.",
    howToUse: "Describe the tool/dashboard and constraints; skill returns a runnable single-file (or small) HTML artifact.",
    useCases: ["Unit converter mini-app","Internal metrics dashboard demo","Calculator for a sales playbook","Prototype for stakeholder demos"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://www.browseract.com/blog/best-claude-skills"],
  },
  {
    slug: "web-design-guidelines",
    name: "Vercel Web Design Guidelines",
    type: "skill",
    summary: "Audits UI code against 100+ Web Interface Guidelines (a11y, performance, UX) and reports terse `file:line` findings—quality gate, not creative direction.",
    categories: ["design","engineering","product"],
    industries: ["saas","other"],
    link: "https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines",
    installation: "```bash\n/plugin marketplace add vercel-labs/agent-skills\n/plugin menu\n# or: cp agent-skills/skills/web-design-guidelines ~/.claude/skills/\n```",
    howToUse: "```text\n/web-design-guidelines src/components/**/*.tsx\n```\nOr ask to audit forms/pages for WCAG/web interface best practices.",
    useCases: ["Pre-a11y-audit UI review","Check focus states and ARIA","Touch target / reduced-motion audit","Design-system consistency gate"],
    sources: ["https://snyk.io/articles/top-claude-skills-ui-ux-engineers/"],
  },
  {
    slug: "webapp-testing",
    name: "Webapp Testing",
    type: "skill",
    summary: "Drives Playwright sessions to navigate flows, capture screenshots, read the accessibility tree, and report structured UI failures—smoke tests without hand-written CI YAML.",
    categories: ["engineering","product","other"],
    industries: ["saas","ecommerce","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    installation: "```bash\n/plugin install webapp-testing@anthropic-agent-skills\n```\nSandbox the browser.",
    howToUse: "```text\n/webapp-testing http://localhost:3000 \"verify login flow and dashboard render\"\n```\nOr ask Claude to smoke-test staging with this skill.",
    useCases: ["Nightly UI smoke tests via Routines","Verify login + dashboard after a diff","Catch unclickable overlays via a11y tree","Screenshot-based regression checks"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f"],
  },
  {
    slug: "workflow-visualizer",
    name: "Workflow Visualizer",
    type: "skill",
    summary: "Maps a process, business system, or operating setup into an interactive visual with phases, triggers, components, and connected tools.",
    categories: ["operations","product","other"],
    industries: ["saas","agency","other"],
    link: "https://artificialcorner.com/p/claude-skills",
    installation: "Upload skill zip from Artificial Corner; enable in Claude Skills.",
    howToUse: "Describe the process/system; skill produces an interactive visual map rather than a flat step list.",
    useCases: ["Map onboarding ops","Document a tool-connected GTM system","Find breakage points in a handoff","Explain a system to new hires"],
    sources: ["https://artificialcorner.com/p/claude-skills"],
  },
  {
    slug: "xlsx",
    name: "XLSX / Excel Spreadsheets",
    type: "skill",
    summary: "Builds real Excel workbooks with formulas, analysis, charts, and formatting from natural language—bridging raw data and usable spreadsheets.",
    categories: ["operations","growth","other"],
    industries: ["saas","ecommerce","fintech","other"],
    link: "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    installation: "```bash\n/plugin install document-skills@anthropic-agent-skills\n```",
    howToUse: "Describe the dataset and analysis goals; combine with pptx to turn spreadsheets into executive decks.",
    useCases: ["Regional comparative analysis workbook","Financial model with formulas and charts","Clean and chart a CSV export","KPI tracker template for ops"],
    sources: ["https://dev.to/suraj_khaitan_f893c243958/i-tried-100-claude-skills-these-are-the-best-1m4a","https://medium.com/data-science-collective/the-8-skills-every-claude-code-setup-needs-in-2026-eb7e72cbf91f","https://www.browseract.com/blog/best-claude-skills","https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
  {
    slug: "zapier-skills",
    name: "Zapier Skills for Claude",
    type: "skill",
    summary: "Zapier partner skills from Anthropic’s Partner Skills Directory—teach reliable automation workflows on top of Zapier MCP/tools.",
    categories: ["operations","growth","other"],
    industries: ["saas","agency","ecommerce","other"],
    link: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    installation: "Enable Zapier partner skill and connect Zapier MCP/integration in Claude.",
    howToUse: "Describe the automation outcome; skill guides multi-step Zapier orchestration.",
    useCases: ["Lead routing automation","Slack↔CRM sync design","Form-to-pipeline zaps","Ops glue workflows"],
    sources: ["https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf"],
  },
];
