import type { Category, DirectoryEntry, EntryType, Industry } from "./types";

/**
 * Large curated GitHub catalog (AI, anti-AI, design, growth, sales, marketing, development).
 * SEO: each entry has githubRepo + resourceUrl in page copy/metadata.
 * Live GitHub outbound links; SEO via githubRepo + resourceUrl.
 */

type Spec = {
  repo: string;
  name: string;
  type: EntryType;
  categories: Category[];
  industries: Industry[];
  blurb: string;
  exampleIntro: string;
  steps: [string, string, string] | [string, string, string, string];
  prompts: [string, string, string];
  prerequisites: string[];
  tips: string[];
  stars: string;
  group: string;
};

function entryFromSpec(spec: Spec): DirectoryEntry {
  const githubUrl = `https://github.com/${spec.repo}`;
  const slug = spec.repo
    .toLowerCase()
    .replace(/\//g, "-")
    .replace(/\./g, "-")
    .replace(/_/g, "-");
  const steps = spec.steps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  return {
    slug,
    name: spec.name,
    type: spec.type,
    githubRepo: spec.repo,
    resourceUrl: githubUrl,
    summary: `${spec.blurb} GitHub: ${spec.repo} (~${spec.stars} stars).`,
    overview: [
      `${spec.name} is the open-source project at ${spec.repo} on GitHub (${githubUrl}).`,
      "",
      spec.blurb,
      "",
      `Category on LimeDock: ${spec.group}. Approximate community size: ~${spec.stars} GitHub stars.`,
      "",
      `Repo (copy/paste): ${githubUrl}`,
      "",
      "This LimeDock Directories page explains what it is and how teams use it in plain English — so searches for the GitHub project can land on a practical guide.",
    ].join("\n"),
    categories: spec.categories,
    industries: spec.industries,
    link: githubUrl,
    installation: [
      "Open the GitHub repository, then follow the README for your stack.",
      "",
      `Official GitHub repository: ${githubUrl}`,
      `GitHub path: ${spec.repo}`,
      "",
      "How to open it:",
      `1. Copy this URL: ${githubUrl}`,
      "2. Clone or follow the README install for your OS / stack.",
      "3. Start with the smallest example in their docs before production use.",
    ].join("\n"),
    howToUse: ["**Simple example**", spec.exampleIntro, "", steps].join("\n"),
    useCases: [
      `Evaluate ${spec.repo} for your stack`,
      `Onboard a teammate to ${spec.name} with a shared checklist`,
      `Compare ${spec.name} against tools you already pay for`,
      "Capture lessons in your internal wiki after a pilot",
    ],
    examplePrompts: [...spec.prompts],
    prerequisites: spec.prerequisites,
    tips: spec.tips,
    sources: [],
  };
}

const SPECS: Spec[] = [
  {
    repo: "openclaw/openclaw",
    name: "OpenClaw",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Open agent platform / skill ecosystem for wiring AI agents into real workflows.",
    exampleIntro: "You want an agent that can use OpenClaw skills instead of inventing steps every time.",
    steps: ["Clone openclaw/openclaw and skim the README for the install path that matches your agent host.", "Ask your coding agent: \u201cSet up OpenClaw skills for our repo and list what we can invoke.\u201d", "Run one small task end-to-end before enabling write access to tools."] as Spec["steps"],
    prompts: ["What is OpenClaw and when should a SaaS team use it?", "Install OpenClaw and show the first skill I should try.", "Compare OpenClaw vs keeping skills only in ~/.claude/skills."] as Spec["prompts"],
    prerequisites: ["Git + a compatible agent host", "Time to read the repo\u2019s security notes before connecting tools"],
    tips: ["Start read-only.", "Treat community skills like dependencies \u2014 audit before production."],
    stars: "386k",
    group: "ai-powered",
  },
  {
    repo: "obra/superpowers",
    name: "Superpowers",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Composable Claude Code / agent skill pack (\u201csuperpowers\u201d) for planning, debugging, and shipping.",
    exampleIntro: "Your agent keeps forgetting a reliable debug \u2192 plan \u2192 ship loop.",
    steps: ["Clone obra/superpowers (or install via the repo\u2019s skill instructions).", "Enable the pack in Claude Code / your agent.", "Say: \u201cUse Superpowers to investigate this failing test and propose a fix plan.\u201d"] as Spec["steps"],
    prompts: ["Install Superpowers and run a debug loop on this stack trace.", "Which Superpowers skill should I use for a multi-step feature plan?", "Audit Superpowers skills before enabling them globally."] as Spec["prompts"],
    prerequisites: ["Claude Code or Agent Skills\u2013compatible host", "Willingness to review SKILL.md files"],
    tips: ["Already popular in agent communities \u2014 still audit scripts.", "Pair with your own product context file."],
    stars: "270k",
    group: "ai-powered",
  },
  {
    repo: "affaan-m/ECC",
    name: "ECC",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Agent skill / capability pack (ECC) for structured engineering workflows with coding agents.",
    exampleIntro: "You want a named playbook pack instead of ad-hoc prompts for engineering chores.",
    steps: ["Open https://github.com/affaan-m/ECC", "Install per README into your agent skills folder.", "Invoke ECC on one recurring task (review, scaffold, or refactor)."] as Spec["steps"],
    prompts: ["Explain what ECC provides in plain English.", "Install ECC and run it on this PR review.", "When is ECC better than a one-off prompt?"] as Spec["prompts"],
    prerequisites: ["Compatible coding agent", "Git access"],
    tips: ["Read the skill descriptions before bulk-installing.", "Keep one pack as house style to avoid conflicts."],
    stars: "239k",
    group: "ai-powered",
  },
  {
    repo: "mattpocock/skills",
    name: "Matt Pocock Skills",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Skills pack from Matt Pocock for TypeScript / AI engineering workflows with coding agents.",
    exampleIntro: "Your team writes TS daily and wants agent skills that match modern TypeScript practice.",
    steps: ["Clone mattpocock/skills.", "Install the skills your stack needs.", "Ask: \u201cUse these skills to refactor this module toward clearer types.\u201d"] as Spec["steps"],
    prompts: ["Which Matt Pocock skills fit a Next.js + TypeScript SaaS?", "Install the pack and propose a first workflow.", "Review this types file using the installed skills."] as Spec["prompts"],
    prerequisites: ["TypeScript codebase", "Agent Skills host"],
    tips: ["Don\u2019t install every skill \u2014 pick the ones you\u2019ll actually trigger.", "Great companion to internal engineering standards."],
    stars: "211k",
    group: "ai-powered",
  },
  {
    repo: "multica-ai/andrej-karpathy-skills",
    name: "Andrej Karpathy Skills",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Skill pack inspired by Andrej Karpathy\u2013style learning / LLM engineering practices for agents.",
    exampleIntro: "You want the agent to coach learning and LLM fundamentals with a structured skill pack.",
    steps: ["Clone the repo.", "Install into your agent.", "Ask it to walk a Karpathy-style learning path on a topic you choose."] as Spec["steps"],
    prompts: ["Use Andrej Karpathy skills to outline a week-1 LLM learning plan.", "Turn this concept into exercises in Karpathy style.", "What skills are in this pack?"] as Spec["prompts"],
    prerequisites: ["Curiosity + an agent host", "Basic Python helps for deeper labs"],
    tips: ["Use for learning loops, not as production infra.", "Combine with note-taking so lessons stick."],
    stars: "201k",
    group: "ai-powered",
  },
  {
    repo: "n8n-io/n8n",
    name: "n8n",
    type: "agent",
    categories: ["operations", "growth", "engineering"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "Open-source workflow automation \u2014 connect apps with visual workflows (self-host or cloud).",
    exampleIntro: "Slack + CRM + Sheets still need a human glue layer every Monday.",
    steps: ["Clone or deploy n8n (Docker is common).", "Connect Slack and your CRM credentials.", "Build: new lead \u2192 enrich \u2192 Slack alert \u2192 CRM note.", "Turn on only after a dry run."] as Spec["steps"],
    prompts: ["Design an n8n flow for after-hours lead alerts to Slack.", "Compare n8n vs Zapier for a self-hosted SaaS ops team.", "What\u2019s the safest first n8n workflow to ship?"] as Spec["prompts"],
    prerequisites: ["Server or n8n cloud", "API keys for the apps you connect", "Someone to own failed runs"],
    tips: ["Start with one workflow and alerting on errors.", "LimeDock still fits when you want owned Slack/CRM automations with a team that ships them."],
    stars: "200k",
    group: "ai-powered",
  },
  {
    repo: "tensorflow/tensorflow",
    name: "TensorFlow",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Google\u2019s open-source machine learning framework for training and serving models.",
    exampleIntro: "You\u2019re past ChatGPT wrappers and need to train or serve a real model.",
    steps: ["Install TensorFlow in a clean Python env.", "Run an official beginner tutorial notebook.", "Swap in a tiny dataset from your product (with privacy review)."] as Spec["steps"],
    prompts: ["Explain TensorFlow vs PyTorch for a SaaS ML newbie.", "Set up TensorFlow and run the first official tutorial.", "When should we not use TensorFlow?"] as Spec["prompts"],
    prerequisites: ["Python + GPU optional", "ML problem worth the complexity"],
    tips: ["Most GTM teams don\u2019t need this \u2014 agents/tools first.", "Use when you own model training, not just prompting."],
    stars: "197k",
    group: "ai-powered",
  },
  {
    repo: "Significant-Gravitas/AutoGPT",
    name: "AutoGPT",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Autonomous agent framework for goal-driven multi-step tasks with tools and memory.",
    exampleIntro: "You want to experiment with an agent that plans and loops toward a goal (with supervision).",
    steps: ["Clone AutoGPT and follow the current README (project evolves fast).", "Configure model keys + tool permissions tightly.", "Give a narrow goal with a hard stop condition."] as Spec["steps"],
    prompts: ["Give AutoGPT a narrow research goal with a stop rule.", "What guardrails should we set before enabling tools?", "Compare AutoGPT vs a single Claude Code session for chores."] as Spec["prompts"],
    prerequisites: ["API keys", "Sandbox / limited credentials", "Human review of actions"],
    tips: ["Never give production write credentials on day one.", "Narrow goals beat \u201cbuild my startup.\u201d"],
    stars: "186k",
    group: "ai-powered",
  },
  {
    repo: "ollama/ollama",
    name: "Ollama",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Run open LLMs locally with a simple CLI and API \u2014 pull a model, chat, integrate.",
    exampleIntro: "You want local models for privacy or offline demos without cloud bills.",
    steps: ["Install Ollama for your OS.", "Run `ollama pull` for a small model.", "Chat locally, then point an app at the local API."] as Spec["steps"],
    prompts: ["Install Ollama and pull a beginner-friendly model.", "How do I expose Ollama to our local Next.js app?", "Which model size fits 16GB RAM?"] as Spec["prompts"],
    prerequisites: ["Enough RAM/disk for model weights", "Local machine or server"],
    tips: ["Start small (tiny models) before 70B dreams.", "Great for private prototyping."],
    stars: "178k",
    group: "ai-powered",
  },
  {
    repo: "microsoft/markitdown",
    name: "MarkItDown",
    type: "skill",
    categories: ["engineering", "operations", "marketing"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Microsoft tool to convert PDFs, Office files, images, and more into Markdown for LLM pipelines.",
    exampleIntro: "Your RAG / agent stack chokes on PDFs and Word docs.",
    steps: ["Install MarkItDown per README.", "Convert one PDF to Markdown.", "Feed the Markdown to your agent or search index."] as Spec["steps"],
    prompts: ["Convert this PDF to clean Markdown with MarkItDown.", "How does MarkItDown fit a RAG ingest pipeline?", "Batch-convert a folder of decks to Markdown."] as Spec["prompts"],
    prerequisites: ["Python environment", "Files you have rights to process"],
    tips: ["Preview output \u2014 OCR/layout can be messy.", "Pair with chunking before embedding."],
    stars: "173k",
    group: "ai-powered",
  },
  {
    repo: "anthropics/skills",
    name: "Anthropic Skills",
    type: "skill",
    categories: ["engineering", "product", "design"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Official Anthropic example skills for Claude \u2014 design, docs, and agent skill patterns.",
    exampleIntro: "You want canonical skill examples before inventing your own SKILL.md format.",
    steps: ["Browse anthropics/skills.", "Install or copy the example skills you need.", "Use them as templates for your internal skills."] as Spec["steps"],
    prompts: ["Which Anthropic example skills should a design-heavy SaaS install first?", "Copy the brand-guidelines pattern for our tokens.", "Explain the SKILL.md conventions used here."] as Spec["prompts"],
    prerequisites: ["Claude Code / Claude.ai Skills", "Time to customize examples to your brand"],
    tips: ["Examples are starting points \u2014 replace Anthropic brand with yours.", "Audit before enabling all examples."],
    stars: "167k",
    group: "ai-powered",
  },
  {
    repo: "f/prompts.chat",
    name: "prompts.chat",
    type: "skill",
    categories: ["product", "marketing", "other"] as Category[],
    industries: ["saas", "agency", "education", "other"] as Industry[],
    blurb: "Open prompt library / chat prompt collection for discovering and sharing useful prompts.",
    exampleIntro: "Your team reinvented the same prompt for the tenth time.",
    steps: ["Open the repo / site from f/prompts.chat.", "Search for a prompt matching your task.", "Adapt it into your agent skill or team prompt library."] as Spec["steps"],
    prompts: ["Find a prompt for SaaS competitor teardown.", "Turn this prompts.chat entry into a Claude skill.", "How should we organize an internal prompt library?"] as Spec["prompts"],
    prerequisites: ["Browser or clone", "Editorial judgment \u2014 prompts aren\u2019t magic"],
    tips: ["Save winners into skills so they don\u2019t die in Slack.", "Prefer prompts with clear inputs/outputs."],
    stars: "167k",
    group: "ai-powered",
  },
  {
    repo: "AUTOMATIC1111/stable-diffusion-webui",
    name: "Stable Diffusion WebUI",
    type: "skill",
    categories: ["design", "marketing"] as Category[],
    industries: ["agency", "ecommerce", "saas", "other"] as Industry[],
    blurb: "Popular browser UI for Stable Diffusion image generation, extensions, and local workflows.",
    exampleIntro: "Design needs image variants without waiting on a shared Midjourney seat.",
    steps: ["Install the WebUI per OS instructions.", "Load a model you have rights to use.", "Generate a few brand-safe concepts, then pick winners in Figma."] as Spec["steps"],
    prompts: ["Set up AUTOMATIC1111 for local brand moodboards.", "What extensions matter for product UI mockups?", "How do we keep generations on-brand?"] as Spec["prompts"],
    prerequisites: ["GPU recommended", "Disk for models", "Brand/legal review for training & outputs"],
    tips: ["Local \u2260 unlimited license \u2014 check model licenses.", "Human art direction still wins."],
    stars: "164k",
    group: "ai-powered",
  },
  {
    repo: "firecrawl/firecrawl",
    name: "Firecrawl",
    type: "agent",
    categories: ["engineering", "growth", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "API and open-source toolkit to scrape, crawl, and turn websites into LLM-ready markdown.",
    exampleIntro: "Your agent needs clean page content, not raw HTML soup.",
    steps: ["Sign up / self-host Firecrawl per docs.", "Scrape one URL to Markdown.", "Pass that Markdown into Claude for summary or extraction."] as Spec["steps"],
    prompts: ["Scrape this pricing page to Markdown with Firecrawl.", "Crawl our docs site for RAG ingest.", "When to scrape vs use a site\u2019s official API?"] as Spec["prompts"],
    prerequisites: ["API key or self-host capacity", "Respect robots/ToS and rate limits"],
    tips: ["Prefer official APIs when available.", "Cache results \u2014 don\u2019t re-crawl every prompt."],
    stars: "164k",
    group: "ai-powered",
  },
  {
    repo: "huggingface/transformers",
    name: "Hugging Face Transformers",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "The standard Python library for pretrained NLP/vision/audio models on Hugging Face.",
    exampleIntro: "You need to run or fine-tune an open model in Python, not just call a chat API.",
    steps: ["`pip install transformers` in a venv.", "Run a pipeline example (sentiment, summarization).", "Swap in a model ID from the Hub that fits your license needs."] as Spec["steps"],
    prompts: ["Run a Transformers summarization pipeline on this text.", "Explain Transformers vs calling OpenAI for our use case.", "Pick a small model for CPU inference."] as Spec["prompts"],
    prerequisites: ["Python", "GPU optional", "License review for model weights"],
    tips: ["Start with pipelines before custom trainer loops.", "Watch model card licenses."],
    stars: "164k",
    group: "ai-powered",
  },
  {
    repo: "langflow-ai/langflow",
    name: "Langflow",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Visual builder for LLM flows \u2014 drag nodes for prompts, tools, and RAG without starting from a blank repo.",
    exampleIntro: "Non-experts need to prototype an agent flow your engineers can later harden.",
    steps: ["Run Langflow locally or in the cloud.", "Build: retrieve docs \u2192 prompt \u2192 output.", "Export / hand off to eng when the flow proves value."] as Spec["steps"],
    prompts: ["Build a Langflow RAG flow over our help center.", "When should we graduate from Langflow to code?", "Add a tool node that calls our HTTP API."] as Spec["prompts"],
    prerequisites: ["Docker or supported install", "LLM API keys"],
    tips: ["Prototype here; productionize with tests and observability.", "Version your flows."],
    stars: "153k",
    group: "ai-powered",
  },
  {
    repo: "langgenius/dify",
    name: "Dify",
    type: "agent",
    categories: ["engineering", "product", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source LLM app platform \u2014 build assistants, RAG, and agent apps with a product UI.",
    exampleIntro: "You want an internal AI app with auth, knowledge, and tools without building the whole console.",
    steps: ["Deploy Dify.", "Create an app, upload a knowledge base.", "Invite teammates to try the assistant.", "Iterate prompts before custom code."] as Spec["steps"],
    prompts: ["Deploy Dify and create a support assistant over our docs.", "Compare Dify vs Langflow for an internal tools team.", "How do we add a custom tool to Dify?"] as Spec["prompts"],
    prerequisites: ["Server resources", "Model provider keys", "Doc corpus for RAG"],
    tips: ["Great for internal apps; still own your data retention policy.", "Monitor hallucinations on customer-facing use."],
    stars: "152k",
    group: "ai-powered",
  },
  {
    repo: "open-webui/open-webui",
    name: "Open WebUI",
    type: "agent",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Self-hosted ChatGPT-style UI that talks to Ollama and other model backends.",
    exampleIntro: "You want a private chat UI for the team on top of local or self-hosted models.",
    steps: ["Deploy Open WebUI.", "Point it at Ollama or your OpenAI-compatible endpoint.", "Share with the team behind SSO/VPN."] as Spec["steps"],
    prompts: ["Set up Open WebUI + Ollama for our team.", "How do we add RAG docs in Open WebUI?", "Hardening checklist for a private WebUI deploy."] as Spec["prompts"],
    prerequisites: ["Host machine/server", "Model backend (Ollama, etc.)", "Access control plan"],
    tips: ["Don\u2019t expose publicly without auth.", "Pair with Ollama for a full local stack."],
    stars: "148k",
    group: "ai-powered",
  },
  {
    repo: "langchain-ai/langchain",
    name: "LangChain",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Popular framework for composing LLM apps \u2014 chains, agents, tools, and retrieval.",
    exampleIntro: "Engineers need a standard way to wire prompts, tools, and RAG in code.",
    steps: ["Install langchain packages for your language.", "Build a tiny retrieval QA over 3 markdown files.", "Add one tool and evaluate failure modes."] as Spec["steps"],
    prompts: ["Scaffold a LangChain RAG app over our docs folder.", "LangChain vs plain SDK calls \u2014 when is it worth it?", "Add tracing before we scale this agent."] as Spec["prompts"],
    prerequisites: ["Python or JS competence", "API keys", "Eval mindset"],
    tips: ["Frameworks add power and complexity \u2014 start thin.", "Invest in evals early."],
    stars: "144k",
    group: "ai-powered",
  },
  {
    repo: "msitarzewski/agency-agents",
    name: "Agency Agents",
    type: "agent",
    categories: ["marketing", "operations", "product"] as Category[],
    industries: ["agency", "saas", "other"] as Industry[],
    blurb: "Collection of agency-style AI agent personas/workflows for marketing and delivery teams.",
    exampleIntro: "An agency wants reusable agent roles (strategist, copy, QA) instead of one generic chat.",
    steps: ["Clone the repo.", "Pick one persona that matches a real retainer workflow.", "Run a pilot job with human review gates."] as Spec["steps"],
    prompts: ["Which agency-agent persona fits weekly content production?", "Adapt this persona into a Claude skill for our studio.", "Where do humans still approve?"] as Spec["prompts"],
    prerequisites: ["Agent host", "Client/brand context", "Review checklist"],
    tips: ["Personas \u2260 autopilot \u2014 keep client approval.", "Customize voice per client."],
    stars: "141k",
    group: "ai-powered",
  },
  {
    repo: "Shubhamsaboo/awesome-llm-apps",
    name: "Awesome LLM Apps",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Curated showcase of LLM app examples and patterns to steal for your own builds.",
    exampleIntro: "You need inspiration for what to build before writing architecture docs.",
    steps: ["Browse the awesome list.", "Star 3 apps closest to your use case.", "Clone one example and swap in your data."] as Spec["steps"],
    prompts: ["Pick 3 awesome-llm-apps examples for B2B support automation.", "What pattern fits our PDF \u2192 insights tool?", "Summarize the categories in this awesome list."] as Spec["prompts"],
    prerequisites: ["Time to browse", "Ability to run example stacks"],
    tips: ["Examples age \u2014 verify dependencies.", "Steal patterns, not unbounded scope."],
    stars: "132k",
    group: "ai-powered",
  },
  {
    repo: "garrytan/gstack",
    name: "gstack",
    type: "skill",
    categories: ["engineering", "product", "growth"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Garry Tan\u2019s gstack skill/tooling pack for agent-native building and founder workflows.",
    exampleIntro: "Founders want an opinionated agent stack for building and iterating products faster.",
    steps: ["Open garrytan/gstack.", "Install per README.", "Run the recommended first workflow on a small feature."] as Spec["steps"],
    prompts: ["Install gstack and outline a one-day build plan.", "What problems is gstack optimized for?", "Adapt gstack defaults to our SaaS monorepo."] as Spec["prompts"],
    prerequisites: ["Coding agent", "A real product problem"],
    tips: ["Opinionated stacks work best when you follow the grain.", "Don\u2019t bolt on every tool on day one."],
    stars: "127k",
    group: "ai-powered",
  },
  {
    repo: "github/spec-kit",
    name: "Spec Kit",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "GitHub\u2019s spec-kit for spec-driven development with agents \u2014 specify, plan, then implement.",
    exampleIntro: "PRs are messy because agents code before the spec is clear.",
    steps: ["Clone github/spec-kit.", "Follow the specify \u2192 plan \u2192 implement flow on a small ticket.", "Keep the spec in-repo as the source of truth."] as Spec["steps"],
    prompts: ["Use Spec Kit to write a spec for this feature request.", "Turn this vague ticket into a Spec Kit plan.", "How do we enforce spec-first in Claude Code?"] as Spec["prompts"],
    prerequisites: ["GitHub-centric workflow", "Team buy-in for specs before code"],
    tips: ["Specs prevent agent thrash.", "Start with bugs/features that have clear acceptance tests."],
    stars: "126k",
    group: "ai-powered",
  },
  {
    repo: "Comfy-Org/ComfyUI",
    name: "ComfyUI",
    type: "agent",
    categories: ["design", "marketing"] as Category[],
    industries: ["agency", "ecommerce", "other"] as Industry[],
    blurb: "Node-based UI for advanced Stable Diffusion / generative image workflows.",
    exampleIntro: "Design needs repeatable image pipelines (consistent characters, product shots), not one-off prompts.",
    steps: ["Install ComfyUI.", "Load a simple text-to-image workflow.", "Save the workflow JSON as your team\u2019s template."] as Spec["steps"],
    prompts: ["Build a ComfyUI workflow for consistent product hero shots.", "ComfyUI vs AUTOMATIC1111 for our studio?", "How do we version workflow JSON in git?"] as Spec["prompts"],
    prerequisites: ["GPU", "Model licenses", "Someone to own templates"],
    tips: ["Version workflows like code.", "Lock seeds/models for brand consistency."],
    stars: "126k",
    group: "ai-powered",
  },
  {
    repo: "ggml-org/llama.cpp",
    name: "llama.cpp",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "C/C++ inference engine to run Llama and other LLMs efficiently on CPUs and consumer hardware.",
    exampleIntro: "You need local inference without Python ML stacks.",
    steps: ["Build llama.cpp for your OS.", "Download a GGUF model you can use.", "Run a local CLI chat, then integrate the server API if needed."] as Spec["steps"],
    prompts: ["Build llama.cpp and run a small GGUF model.", "When to choose llama.cpp vs Ollama?", "Tune threads/context for a 16GB machine."] as Spec["prompts"],
    prerequisites: ["Build tools (cmake/make)", "Disk for GGUF models"],
    tips: ["Ollama is friendlier; llama.cpp is more controllable.", "Watch model licenses."],
    stars: "123k",
    group: "ai-powered",
  },
  {
    repo: "microsoft/generative-ai-for-beginners",
    name: "Generative AI for Beginners",
    type: "skill",
    categories: ["engineering", "product", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Microsoft\u2019s free curriculum for generative AI fundamentals \u2014 lessons and hands-on projects.",
    exampleIntro: "The team can use ChatGPT but can\u2019t explain embeddings, tokens, or grounding.",
    steps: ["Clone the curriculum.", "Schedule lessons like a course.", "Do each lab before moving on."] as Spec["steps"],
    prompts: ["Summarize lesson 1 for our non-technical GTM team.", "Build a workshop agenda from this curriculum.", "Which lessons matter before we ship a RAG bot?"] as Spec["prompts"],
    prerequisites: ["Time on calendar", "GitHub + optional Azure/OpenAI access for labs"],
    tips: ["Pair with AI-For-Beginners if you need broader AI, not only genAI.", "Ship a tiny internal demo after week 2."],
    stars: "117k",
    group: "ai-powered",
  },
  {
    repo: "browser-use/browser-use",
    name: "Browser Use",
    type: "agent",
    categories: ["engineering", "operations", "growth"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Make AI agents operate a real browser \u2014 click, type, navigate \u2014 for web tasks APIs don\u2019t cover.",
    exampleIntro: "The workflow only exists in a UI (no API), and you\u2019re tired of doing it by hand.",
    steps: ["Install browser-use per README.", "Run a scripted task on a staging site.", "Add assertions; never point at production credentials first."] as Spec["steps"],
    prompts: ["Automate filling this staging form with browser-use.", "When is browser-use better than Playwright scripts?", "Safety checklist for agent browser control."] as Spec["prompts"],
    prerequisites: ["Python env", "Browser dependencies", "Staging accounts"],
    tips: ["UI automation is brittle \u2014 prefer APIs.", "Log every action for audit."],
    stars: "109k",
    group: "ai-powered",
  },
  {
    repo: "openai/whisper",
    name: "Whisper",
    type: "agent",
    categories: ["engineering", "marketing", "operations"] as Category[],
    industries: ["saas", "agency", "education", "other"] as Industry[],
    blurb: "OpenAI\u2019s open speech-to-text model for transcription in many languages.",
    exampleIntro: "You have customer calls / YouTube drafts that need transcripts for notes and content.",
    steps: ["Install Whisper (or use a hosted runtime).", "Transcribe one short audio file.", "Pipe the transcript into your notes or CMS draft flow."] as Spec["steps"],
    prompts: ["Transcribe this MP3 with Whisper.", "Whisper vs cloud STT for privacy-sensitive calls?", "Batch-transcribe a folder of interview audio."] as Spec["prompts"],
    prerequisites: ["Audio files you may process", "CPU/GPU for local runs"],
    tips: ["Check consent/recording laws.", "Local Whisper helps privacy; cloud may be faster."],
    stars: "107k",
    group: "ai-powered",
  },
  {
    repo: "google-gemini/gemini-cli",
    name: "Gemini CLI",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Official Google Gemini command-line tool for chatting and agentic tasks in the terminal.",
    exampleIntro: "You want Gemini in the terminal beside your git workflow.",
    steps: ["Install gemini-cli per README.", "Authenticate with Google AI credentials.", "Run a repo question from the project root."] as Spec["steps"],
    prompts: ["Install Gemini CLI and ask it to explain this repo\u2019s structure.", "Gemini CLI vs Claude Code for our stack?", "How do we script Gemini CLI in CI safely?"] as Spec["prompts"],
    prerequisites: ["Google AI access", "Terminal comfort"],
    tips: ["Don\u2019t paste secrets into prompts.", "Use for exploration; keep reviews human."],
    stars: "106k",
    group: "ai-powered",
  },
  {
    repo: "rasbt/LLMs-from-scratch",
    name: "LLMs from Scratch",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Sebastian Raschka\u2019s book/code repo teaching how LLMs work by building them from scratch.",
    exampleIntro: "Engineers want real understanding, not only API wrappers.",
    steps: ["Clone the repo / follow the book chapters.", "Run chapter notebooks in order.", "Write a one-pager of what you learned for the team."] as Spec["steps"],
    prompts: ["Outline a 4-week study plan for LLMs-from-scratch.", "Explain attention using this repo\u2019s approach.", "Which chapters matter before fine-tuning?"] as Spec["prompts"],
    prerequisites: ["Python + patience", "Willingness to do exercises"],
    tips: ["Best ROI for ML-curious engineers.", "Don\u2019t confuse learning code with production serving."],
    stars: "102k",
    group: "ai-powered",
  },
  {
    repo: "vllm-project/vllm",
    name: "vLLM",
    type: "agent",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "High-throughput LLM serving engine for production inference (PagedAttention).",
    exampleIntro: "Prototypes work in notebooks; you now need faster multi-user model serving.",
    steps: ["Deploy vLLM with a supported model.", "Hit the OpenAI-compatible API from your app.", "Load-test before marketing the feature."] as Spec["steps"],
    prompts: ["Deploy vLLM for a 7B model on our GPU box.", "vLLM vs Ollama for a multi-user internal app?", "Tuning tips for latency vs throughput."] as Spec["prompts"],
    prerequisites: ["GPU server", "Model license", "Ops ownership"],
    tips: ["Serving \u2260 training.", "Put auth in front of any public endpoint."],
    stars: "89k",
    group: "ai-powered",
  },
  {
    repo: "addyosmani/agent-skills",
    name: "Addy Osmani Agent Skills",
    type: "skill",
    categories: ["engineering", "design", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Agent skills pack from Addy Osmani focused on web engineering / UX quality workflows.",
    exampleIntro: "Frontend agents produce sloppy UI unless guided by strong engineering skills.",
    steps: ["Clone addyosmani/agent-skills.", "Install relevant skills.", "Run them on a UI PR before merge."] as Spec["steps"],
    prompts: ["Which agent-skills should we enable for Next.js UI work?", "Review this component with Addy\u2019s skills loaded.", "Turn our design QA checklist into a matching skill."] as Spec["prompts"],
    prerequisites: ["Frontend repo", "Agent Skills host"],
    tips: ["Pair with anti-slop / a11y skills.", "Keep performance budgets explicit."],
    stars: "85k",
    group: "ai-powered",
  },
  {
    repo: "OpenHands/OpenHands",
    name: "OpenHands",
    type: "agent",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Open-source AI software-development agent that can plan and edit codebases (formerly OpenDevin).",
    exampleIntro: "You want an open coding agent you can self-host and inspect.",
    steps: ["Follow OpenHands install docs.", "Point it at a sample repo with limited permissions.", "Give a small issue; review the diff like a junior PR."] as Spec["steps"],
    prompts: ["Run OpenHands on this good-first-issue.", "OpenHands vs Claude Code for our team?", "Sandboxing checklist for coding agents."] as Spec["prompts"],
    prerequisites: ["Runtime/sandbox", "LLM keys", "Code review process"],
    tips: ["Always review diffs.", "Least-privilege tokens only."],
    stars: "84k",
    group: "ai-powered",
  },
  {
    repo: "unslothai/unsloth",
    name: "Unsloth",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Faster, more memory-efficient fine-tuning / training helpers for LLMs.",
    exampleIntro: "Fine-tunes OOMs on your GPU and training is too slow.",
    steps: ["Install Unsloth in a training env.", "Follow a fine-tune notebook for a small model.", "Eval before replacing your prompt-only stack."] as Spec["steps"],
    prompts: ["Fine-tune a small model with Unsloth on our support Q&A.", "When is fine-tuning worth it vs better prompting/RAG?", "Estimate VRAM needs for this model."] as Spec["prompts"],
    prerequisites: ["GPU", "Clean dataset", "Eval set"],
    tips: ["Garbage dataset \u2192 garbage model.", "Keep a prompt baseline for comparison."],
    stars: "70k",
    group: "ai-powered",
  },
  {
    repo: "blader/humanizer",
    name: "Humanizer",
    type: "skill",
    categories: ["marketing", "other"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Tools/prompts to rewrite AI text so it reads more human and less templated.",
    exampleIntro: "Your blog drafts scream \u201cChatGPT wrote this.\u201d",
    steps: ["Clone blader/humanizer.", "Run your draft through the humanizer workflow.", "Do a final human edit for facts and voice."] as Spec["steps"],
    prompts: ["Humanize this blog draft without changing the facts.", "Checklist to catch AI tells after Humanizer.", "When is humanizing the wrong fix (rewrite from notes instead)?"] as Spec["prompts"],
    prerequisites: ["Draft text", "Brand voice notes"],
    tips: ["Humanize \u2260 truth \u2014 verify claims.", "Better inputs beat endless rewriting."],
    stars: "35k",
    group: "anti-ai",
  },
  {
    repo: "aloshdenny/reverse-SynthID",
    name: "Reverse SynthID",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Research/tooling related to detecting or working with SynthID-style AI watermarks (handle ethically).",
    exampleIntro: "You\u2019re studying AI content provenance / watermarking \u2014 not trying to evade policy.",
    steps: ["Read the README carefully for intent and limits.", "Use only on content you\u2019re allowed to analyze.", "Document findings for your trust & safety notes."] as Spec["steps"],
    prompts: ["Explain SynthID watermarking in plain English.", "What is reverse-SynthID for, ethically?", "How should publishers think about AI watermarks?"] as Spec["prompts"],
    prerequisites: ["Technical literacy", "Clear ethical/legal scope"],
    tips: ["Do not use to violate platform terms or mislabel content.", "Prefer official Google SynthID docs for production watermarking."],
    stars: "4.7k",
    group: "anti-ai",
  },
  {
    repo: "openai/gpt-2-output-dataset",
    name: "GPT-2 Output Dataset",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Classic OpenAI dataset of GPT-2 outputs for detection / research baselines.",
    exampleIntro: "You\u2019re building or evaluating AI-text detection and need a known dataset.",
    steps: ["Download the dataset from the repo.", "Use it only for research/eval.", "Report metrics honestly (detectors drift)."] as Spec["steps"],
    prompts: ["How do we use gpt-2-output-dataset in a detector eval?", "Why is GPT-2-era data not enough alone in 2026?", "Design a modern eval set beyond this corpus."] as Spec["prompts"],
    prerequisites: ["ML eval skills", "Storage for dataset"],
    tips: ["Old datasets \u2260 modern LLM prose.", "Combine with newer samples."],
    stars: "2.0k",
    group: "anti-ai",
  },
  {
    repo: "lynote-ai/humanize-text",
    name: "Humanize Text",
    type: "skill",
    categories: ["marketing", "other"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Humanize-text tooling aimed at making AI drafts sound more natural.",
    exampleIntro: "Support macros and emails feel robotic after GPT.",
    steps: ["Open the repo and follow usage.", "Humanize one email template.", "A/B with a real teammate\u2019s rewrite."] as Spec["steps"],
    prompts: ["Humanize this customer email template.", "Compare humanize-text vs a brand voice skill.", "What phrases still feel AI after humanizing?"] as Spec["prompts"],
    prerequisites: ["Source draft", "Brand voice examples"],
    tips: ["Keep a human in the loop for customer-facing sends.", "Store before/after for QA."],
    stars: "1.6k",
    group: "anti-ai",
  },
  {
    repo: "Hello-SimpleAI/chatgpt-comparison-detection",
    name: "ChatGPT Comparison Detection",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Research project/datasets around detecting ChatGPT-written text via comparison methods.",
    exampleIntro: "You\u2019re evaluating detector approaches for academic or trust workflows.",
    steps: ["Read the paper/repo methodology.", "Reproduce a baseline experiment if needed.", "Don\u2019t deploy a brittle detector as a single source of truth."] as Spec["steps"],
    prompts: ["Summarize this detection approach for a non-ML PM.", "Limitations of ChatGPT detectors in 2026?", "How should schools use detectors ethically?"] as Spec["prompts"],
    prerequisites: ["Research mindset", "Compute for experiments optional"],
    tips: ["Detectors have false positives \u2014 policy matters more than scores.", "Transparent process > secret sauce."],
    stars: "1.4k",
    group: "anti-ai",
  },
  {
    repo: "google-deepmind/synthid-text",
    name: "SynthID Text",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Google DeepMind\u2019s SynthID for text \u2014 watermarking / detecting AI-generated text in supported setups.",
    exampleIntro: "You need official watermarking research for AI content provenance.",
    steps: ["Read DeepMind\u2019s SynthID text repo/docs.", "Prototype only in supported model/tooling contexts.", "Design product policy around provenance, not gotchas."] as Spec["steps"],
    prompts: ["Explain SynthID Text for our trust team.", "How would we adopt watermarking in our generator?", "SynthID vs classifier-based detectors?"] as Spec["prompts"],
    prerequisites: ["Compatible generation stack", "Policy owners"],
    tips: ["Prefer official APIs/docs for production.", "Watermarks complement, not replace, disclosure."],
    stars: "934",
    group: "anti-ai",
  },
  {
    repo: "mertizci/noai-watermark",
    name: "NoAI Watermark",
    type: "skill",
    categories: ["design", "other"] as Category[],
    industries: ["agency", "other"] as Industry[],
    blurb: "Tooling related to AI image watermark handling \u2014 use only for legitimate ownership/recovery workflows.",
    exampleIntro: "You\u2019re dealing with watermarked AI images in a legitimate design pipeline.",
    steps: ["Read the README and legal constraints.", "Use only on assets you own or have rights to process.", "Prefer generating clean assets over stripping marks."] as Spec["steps"],
    prompts: ["When is noai-watermark appropriate vs regenerating an image?", "What\u2019s the ethical use case?", "Checklist before processing watermarked assets."] as Spec["prompts"],
    prerequisites: ["Rights to the assets", "Clear policy"],
    tips: ["Don\u2019t use to misrepresent AI content as human-only.", "Regenerate with proper license when unsure."],
    stars: "151",
    group: "anti-ai",
  },
  {
    repo: "camaker/remove-ai-watermarks",
    name: "Remove AI Watermarks",
    type: "skill",
    categories: ["design", "other"] as Category[],
    industries: ["agency", "other"] as Industry[],
    blurb: "Community tooling around AI watermark removal \u2014 high misuse risk; treat as research/awareness only.",
    exampleIntro: "You\u2019re researching how watermarks work so your team can set better disclosure policy.",
    steps: ["Read the repo for what it claims.", "Do not use to bypass platform rules or deceive clients.", "Document risks for your studio policy."] as Spec["steps"],
    prompts: ["Explain risks of watermark-removal tools to our studio.", "What should our client contracts say about AI imagery?", "Better alternatives to stripping watermarks?"] as Spec["prompts"],
    prerequisites: ["Strong ethics policy", "Legal review if commercial use"],
    tips: ["LimeDock lists this for awareness \u2014 misuse can violate terms/law.", "Prefer licensed generation + disclosure."],
    stars: "rising",
    group: "anti-ai",
  },
  {
    repo: "excalidraw/excalidraw",
    name: "Excalidraw",
    type: "skill",
    categories: ["design", "product", "engineering"] as Category[],
    industries: ["saas", "agency", "education", "other"] as Industry[],
    blurb: "Open-source virtual whiteboard for hand-drawn diagrams \u2014 great for architecture and workshops.",
    exampleIntro: "The team needs a diagram in 5 minutes, not a Figma project.",
    steps: ["Use excalidraw.com or self-host.", "Sketch the flow live in a meeting.", "Export PNG/SVG into the PR or Notion doc."] as Spec["steps"],
    prompts: ["Diagram our checkout flow in Excalidraw style.", "Self-host Excalidraw for our team?", "Excalidraw vs tldraw for product workshops?"] as Spec["prompts"],
    prerequisites: ["Browser", "Optional self-host"],
    tips: ["Perfect for thinking; promote stable diagrams to formal docs later.", "Keep a component library of recurring shapes."],
    stars: "129k",
    group: "design",
  },
  {
    repo: "shadcn-ui/ui",
    name: "shadcn/ui",
    type: "skill",
    categories: ["design", "engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Copy-paste React component system built on Tailwind \u2014 you own the code in your repo.",
    exampleIntro: "You want polished UI without a black-box component package.",
    steps: ["Init shadcn/ui in your Next/React app.", "Add Button/Dialog/Form as needed.", "Customize tokens to your brand."] as Spec["steps"],
    prompts: ["Add shadcn/ui to this Next.js app.", "Which components should we install first for a settings page?", "How do we theme shadcn to our brand?"] as Spec["prompts"],
    prerequisites: ["React + Tailwind", "Design tokens"],
    tips: ["You own the components \u2014 update deliberately.", "Pair with accessibility checks."],
    stars: "121k",
    group: "design",
  },
  {
    repo: "VoltAgent/awesome-design-md",
    name: "Awesome Design MD",
    type: "skill",
    categories: ["design", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Curated list of design-system / DESIGN.md style resources for agent-friendly design context.",
    exampleIntro: "Agents keep inventing random UI because they lack a DESIGN.md.",
    steps: ["Browse the awesome list.", "Pick a DESIGN.md pattern.", "Add a DESIGN.md to your repo and point the agent at it."] as Spec["steps"],
    prompts: ["Create a DESIGN.md for our SaaS using patterns from this list.", "What should a design-md include for agents?", "Pick 3 resources from awesome-design-md for a startup."] as Spec["prompts"],
    prerequisites: ["A product UI", "Willingness to write design rules down"],
    tips: ["One living DESIGN.md beats 40 screenshots in Slack.", "Keep tokens and don\u2019ts explicit."],
    stars: "107k",
    group: "design",
  },
  {
    repo: "ant-design/ant-design",
    name: "Ant Design",
    type: "skill",
    categories: ["design", "engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Enterprise React UI library with dense, capable components.",
    exampleIntro: "You\u2019re building an admin console and need tables, forms, and patterns fast.",
    steps: ["Install antd in your React app.", "Build one settings form with Ant Form.", "Align theme tokens to brand where possible."] as Spec["steps"],
    prompts: ["Scaffold an admin table page with Ant Design.", "Ant Design vs shadcn for our SaaS admin?", "Theming Ant Design to our palette."] as Spec["prompts"],
    prerequisites: ["React app", "Design opinion tolerance (Ant has a look)"],
    tips: ["Great for internal tools; marketing sites may want a lighter system.", "Don\u2019t fight the defaults everywhere."],
    stars: "99k",
    group: "design",
  },
  {
    repo: "mui/material-ui",
    name: "MUI",
    type: "skill",
    categories: ["design", "engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Material UI React components implementing Google\u2019s Material Design.",
    exampleIntro: "You need a mature React component library with broad ecosystem support.",
    steps: ["Install MUI.", "Wrap the app in a ThemeProvider.", "Build a page with MUI Layout + DataGrid patterns as needed."] as Spec["steps"],
    prompts: ["Set up MUI ThemeProvider with our brand colors.", "MUI vs Chakra for a new dashboard?", "Accessible dialog pattern in MUI."] as Spec["prompts"],
    prerequisites: ["React", "Theme decisions"],
    tips: ["Theming early prevents visual debt.", "Watch bundle size \u2014 import thoughtfully."],
    stars: "99k",
    group: "design",
  },
  {
    repo: "tailwindlabs/tailwindcss",
    name: "Tailwind CSS",
    type: "skill",
    categories: ["design", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Utility-first CSS framework for designing directly in markup.",
    exampleIntro: "CSS files are chaos and you want consistent spacing/type fast.",
    steps: ["Install Tailwind in your framework.", "Define brand colors in the theme.", "Rebuild one page with utilities + extract components."] as Spec["steps"],
    prompts: ["Add Tailwind to this project and migrate one page.", "How should we structure a design token theme in Tailwind?", "Tailwind with shadcn \u2014 starter checklist."] as Spec["prompts"],
    prerequisites: ["Frontend repo", "Design tokens"],
    tips: ["Utilities shine with components \u2014 avoid mega class soup without extraction.", "Lint class order if the team wants consistency."],
    stars: "97k",
    group: "design",
  },
  {
    repo: "storybookjs/storybook",
    name: "Storybook",
    type: "skill",
    categories: ["design", "engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Workshop for building UI components in isolation \u2014 docs, tests, and visual review.",
    exampleIntro: "Components only exist inside pages, so design review is painful.",
    steps: ["Add Storybook to the design system package.", "Write stories for Button/Input.", "Use Storybook as the review surface in PRs."] as Spec["steps"],
    prompts: ["Add Storybook stories for our Button variants.", "How do we catch visual regressions in Storybook?", "Storybook + Chromatic workflow overview."] as Spec["prompts"],
    prerequisites: ["Component library or app UI", "CI willingness"],
    tips: ["Stories are documentation \u2014 keep them honest.", "Gate merges on critical component stories."],
    stars: "91k",
    group: "design",
  },
  {
    repo: "penpot/penpot",
    name: "Penpot",
    type: "skill",
    categories: ["design", "product"] as Category[],
    industries: ["agency", "saas", "other"] as Industry[],
    blurb: "Open-source design tool (Figma-like) for UI design and prototyping you can self-host.",
    exampleIntro: "You want design files without being locked into one vendor.",
    steps: ["Use Penpot cloud or self-host.", "Create a design file for a new settings page.", "Hand off specs/export to engineering."] as Spec["steps"],
    prompts: ["Self-host Penpot for our design team?", "Penpot vs Figma for a small SaaS?", "How do we structure a Penpot design system file?"] as Spec["prompts"],
    prerequisites: ["Designers willing to try a new tool", "Hosting if self-hosted"],
    tips: ["Migration costs are real \u2014 pilot one squad.", "Open-source helps procurement/security reviews."],
    stars: "58k",
    group: "design",
  },
  {
    repo: "tldraw/tldraw",
    name: "tldraw",
    type: "skill",
    categories: ["design", "product", "engineering"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "Infinite canvas SDK / whiteboard for building drawing experiences into products.",
    exampleIntro: "You need whiteboarding in-product, not just a separate Excalidraw tab.",
    steps: ["Try tldraw\u2019s app or embed the SDK.", "Prototype a canvas feature in a spike branch.", "Decide embed vs link-out."] as Spec["steps"],
    prompts: ["Embed a tldraw canvas in our Next.js app.", "tldraw vs Excalidraw for an in-app whiteboard?", "Persistence options for tldraw documents."] as Spec["prompts"],
    prerequisites: ["Frontend eng time", "Product need for canvas"],
    tips: ["SDK power comes with product scope \u2014 start with a spike.", "Great for collaborative sketches."],
    stars: "50k",
    group: "design",
  },
  {
    repo: "chakra-ui/chakra-ui",
    name: "Chakra UI",
    type: "skill",
    categories: ["design", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Accessible React component library with a friendly style props API.",
    exampleIntro: "You want accessible components quickly with less CSS ceremony.",
    steps: ["Install Chakra.", "Wrap with Provider and theme.", "Build a form page using Chakra components."] as Spec["steps"],
    prompts: ["Set up Chakra UI v2/v3 for this app (match docs version).", "Chakra vs MUI for accessibility defaults?", "Create a theme with our brand tokens."] as Spec["prompts"],
    prerequisites: ["React", "Theme tokens"],
    tips: ["Follow the version of Chakra your docs match.", "Accessibility is a feature \u2014 keep it."],
    stars: "41k",
    group: "design",
  },
  {
    repo: "motiondivision/motion",
    name: "Motion",
    type: "skill",
    categories: ["design", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Motion (formerly Framer Motion) \u2014 animation library for React UIs.",
    exampleIntro: "The UI feels static and you need purposeful motion, not random bounce.",
    steps: ["Install `motion`.", "Animate one meaningful transition (page or modal).", "Respect reduced-motion preferences."] as Spec["steps"],
    prompts: ["Add a modal enter/exit with Motion.", "How do we honor prefers-reduced-motion?", "Motion checklist for a marketing landing page."] as Spec["prompts"],
    prerequisites: ["React app", "Design intent for motion"],
    tips: ["Motion should clarify hierarchy \u2014 not decorate everything.", "Always handle reduced motion."],
    stars: "33k",
    group: "design",
  },
  {
    repo: "magicuidesign/magicui",
    name: "Magic UI",
    type: "skill",
    categories: ["design", "marketing", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Marketing UI components / effects for React + Tailwind landing pages.",
    exampleIntro: "Landing pages look generic and you want higher-craft sections fast.",
    steps: ["Browse Magic UI components.", "Install one section (hero, logo cloud, etc.).", "Restyle to brand \u2014 don\u2019t ship the demo look."] as Spec["steps"],
    prompts: ["Add a Magic UI hero pattern to our landing page.", "Which Magic UI components fit a B2B SaaS homepage?", "How do we avoid looking like every other Magic UI site?"] as Spec["prompts"],
    prerequisites: ["React + Tailwind", "Brand direction"],
    tips: ["Customize hard or you\u2019ll look templated.", "Performance-check heavy effects."],
    stars: "22k",
    group: "design",
  },
  {
    repo: "PostHog/posthog",
    name: "PostHog",
    type: "skill",
    categories: ["growth", "product", "engineering"] as Category[],
    industries: ["saas", "ecommerce", "other"] as Industry[],
    blurb: "Open-source product analytics: events, session replay, flags, experiments \u2014 self-host or cloud.",
    exampleIntro: "You can\u2019t answer \u201cwhere do users drop?\u201d without another SaaS bill negotiation.",
    steps: ["Deploy PostHog cloud or self-host.", "Install the JS snippet.", "Track signup \u2192 activation events.", "Watch one replay of a confused user."] as Spec["steps"],
    prompts: ["Define an activation event taxonomy in PostHog.", "PostHog vs Plausible for our stage?", "Set up a feature flag + experiment."] as Spec["prompts"],
    prerequisites: ["Engineering time for events", "Privacy policy update"],
    tips: ["Event naming conventions save you later.", "Replay is sensitive \u2014 handle access carefully."],
    stars: "38k",
    group: "growth",
  },
  {
    repo: "umami-software/umami",
    name: "Umami",
    type: "skill",
    categories: ["growth", "marketing"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Simple, privacy-friendly web analytics you can self-host.",
    exampleIntro: "You want basics (pageviews, referrers) without heavy tracking baggage.",
    steps: ["Deploy Umami.", "Add the script to your site.", "Share a weekly traffic note with marketing."] as Spec["steps"],
    prompts: ["Deploy Umami for limedock.com-style marketing sites.", "Umami vs Plausible?", "What events should we track beyond pageviews?"] as Spec["prompts"],
    prerequisites: ["Hosting", "Script install access"],
    tips: ["Keep it simple \u2014 don\u2019t rebuild PostHog inside Umami.", "Great for marketing sites."],
    stars: "38k",
    group: "growth",
  },
  {
    repo: "plausible/analytics",
    name: "Plausible Analytics",
    type: "skill",
    categories: ["growth", "marketing"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Lightweight, privacy-oriented web analytics (open-source + cloud).",
    exampleIntro: "Marketing wants analytics that don\u2019t require a cookie banner war.",
    steps: ["Use Plausible cloud or self-host.", "Add the script.", "Configure goals for signup clicks."] as Spec["steps"],
    prompts: ["Set up Plausible goals for CTA clicks.", "Plausible vs GA4 for a privacy-first SaaS?", "Self-host Plausible checklist."] as Spec["prompts"],
    prerequisites: ["Domain + script access", "Budget for cloud or host"],
    tips: ["Goals > vanity pageviews.", "Pair with product analytics for in-app funnels."],
    stars: "28k",
    group: "growth",
  },
  {
    repo: "dubinc/dub",
    name: "Dub",
    type: "skill",
    categories: ["growth", "marketing"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "Open-source link management / short links with analytics \u2014 branded links that you control.",
    exampleIntro: "Campaign links are a mess of bit.ly and mystery UTMs.",
    steps: ["Deploy Dub or use Dub cloud.", "Create a branded short link for a campaign.", "Share click analytics with growth weekly."] as Spec["steps"],
    prompts: ["Create a Dub link strategy for product launch UTMs.", "Dub vs Bitly for a B2B SaaS?", "How do we organize Dub links by campaign?"] as Spec["prompts"],
    prerequisites: ["Domain for short links", "Owner for naming conventions"],
    tips: ["Naming conventions matter more than the tool.", "Connect to your CRM/attribution carefully."],
    stars: "24k",
    group: "growth",
  },
  {
    repo: "matomo-org/matomo",
    name: "Matomo",
    type: "skill",
    categories: ["growth", "marketing"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Full-featured open-source web analytics suite you can self-host for data ownership.",
    exampleIntro: "Compliance wants analytics data on your infrastructure.",
    steps: ["Self-host Matomo.", "Install tracking.", "Configure goals and access controls."] as Spec["steps"],
    prompts: ["Self-host Matomo with SSO for our marketing team.", "Matomo vs GA4 for data ownership?", "Which Matomo plugins are worth it?"] as Spec["prompts"],
    prerequisites: ["Server ops", "Privacy/legal review"],
    tips: ["Powerful \u2260 must enable everything.", "Train marketers on the UI."],
    stars: "22k",
    group: "growth",
  },
  {
    repo: "growthbook/growthbook",
    name: "GrowthBook",
    type: "skill",
    categories: ["growth", "engineering", "product"] as Category[],
    industries: ["saas", "ecommerce", "other"] as Industry[],
    blurb: "Open-source feature flags + A/B testing platform for evidence-based growth.",
    exampleIntro: "Experiments live in spreadsheets and flags are tribal knowledge.",
    steps: ["Deploy GrowthBook.", "Wrap a feature in a flag.", "Run a simple A/B with a primary metric."] as Spec["steps"],
    prompts: ["Create a GrowthBook experiment for pricing page CTA.", "GrowthBook vs PostHog experiments?", "Flag hygiene checklist."] as Spec["prompts"],
    prerequisites: ["SDK install", "Metrics source", "Traffic reality"],
    tips: ["Clean up stale flags.", "Hypothesis before variants."],
    stars: "8.1k",
    group: "growth",
  },
  {
    repo: "AgriciDaniel/claude-seo",
    name: "Claude SEO",
    type: "skill",
    categories: ["growth", "marketing"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Claude-focused SEO skill/tooling to audit and improve pages with an agent.",
    exampleIntro: "SEO tasks are repetitive and you want Claude to follow a consistent audit skill.",
    steps: ["Install from the repo\u2019s instructions.", "Point it at a URL or page draft.", "Apply fixes; re-audit."] as Spec["steps"],
    prompts: ["Run Claude SEO on our /directories page.", "Create an SEO checklist skill from this repo.", "What should humans still verify after Claude SEO?"] as Spec["prompts"],
    prerequisites: ["Claude / agent host", "Access to page content"],
    tips: ["SEO agents suggest \u2014 Search Console confirms.", "Don\u2019t keyword-stuff."],
    stars: "14k",
    group: "growth",
  },
  {
    repo: "firecrawl/pdf-inspector",
    name: "PDF Inspector",
    type: "skill",
    categories: ["growth", "engineering", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Firecrawl\u2019s PDF inspector tooling for extracting / inspecting PDF content in agent pipelines.",
    exampleIntro: "Sales decks and reports are PDFs and your agent can\u2019t read them well.",
    steps: ["Follow the repo setup.", "Inspect one PDF.", "Pass extracted text into your CRM note or summary prompt."] as Spec["steps"],
    prompts: ["Inspect this PDF and summarize pricing tables.", "PDF Inspector vs MarkItDown for our pipeline?", "Batch-inspect inbound proposal PDFs."] as Spec["prompts"],
    prerequisites: ["PDFs you may process", "Runtime deps"],
    tips: ["Validate extraction on scanned PDFs.", "Mind PII in documents."],
    stars: "14k",
    group: "growth",
  },
  {
    repo: "meilisearch/meilisearch",
    name: "Meilisearch",
    type: "skill",
    categories: ["growth", "engineering", "product"] as Category[],
    industries: ["saas", "ecommerce", "marketplace", "other"] as Industry[],
    blurb: "Fast, typo-tolerant search engine for product/docs/site search \u2014 easy to self-host.",
    exampleIntro: "Site search is useless and users bounce.",
    steps: ["Run Meilisearch.", "Index docs or catalog JSON.", "Add a search box to the app/docs."] as Spec["steps"],
    prompts: ["Index our docs in Meilisearch.", "Meilisearch vs Typesense for docs search?", "Relevance tuning basics."] as Spec["prompts"],
    prerequisites: ["Hosting", "Structured documents to index"],
    tips: ["Good search needs good records \u2014 clean titles/bodies.", "Typo tolerance is a feature \u2014 test it."],
    stars: "59k",
    group: "growth",
  },
  {
    repo: "typesense/typesense",
    name: "Typesense",
    type: "skill",
    categories: ["growth", "engineering", "product"] as Category[],
    industries: ["saas", "ecommerce", "marketplace", "other"] as Industry[],
    blurb: "Typo-tolerant, fast search engine for building delightful search UX.",
    exampleIntro: "E-commerce/docs search feels dumb and slow.",
    steps: ["Run Typesense.", "Create a collection schema.", "Wire search UI with instant results."] as Spec["steps"],
    prompts: ["Set up Typesense for our help center.", "Typesense vs Meilisearch \u2014 pick for our constraints.", "Faceted search example for a catalog."] as Spec["prompts"],
    prerequisites: ["Hosting", "Schema design time"],
    tips: ["Schema design is the hard part.", "Measure p95 latency early."],
    stars: "26k",
    group: "growth",
  },
  {
    repo: "twentyhq/twenty",
    name: "Twenty",
    type: "skill",
    categories: ["sales", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source Notion-style CRM \u2014 modern alternative to Salesforce for teams who want ownership.",
    exampleIntro: "CRM should be yours, not another rented maze.",
    steps: ["Deploy Twenty.", "Import a CSV of leads.", "Define pipeline stages your sales team actually uses."] as Spec["steps"],
    prompts: ["Migrate a HubSpot export into Twenty (pilot).", "Twenty vs EspoCRM for a 10-person SaaS?", "What objects should we configure first?"] as Spec["prompts"],
    prerequisites: ["Hosting", "Sales process clarity", "Import hygiene"],
    tips: ["CRM fails without stage discipline.", "Pilot with one pod."],
    stars: "55k",
    group: "sales",
  },
  {
    repo: "calcom/cal.com",
    name: "Cal.com",
    type: "skill",
    categories: ["sales", "operations", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source scheduling infrastructure \u2014 booking pages, teams, workflows you can self-host.",
    exampleIntro: "You\u2019re paying for scheduling and still fighting timezone chaos.",
    steps: ["Deploy Cal.com or use hosted.", "Create a sales booking link.", "Route to the right owner with workflows."] as Spec["steps"],
    prompts: ["Set up Cal.com team routing for sales demos.", "Cal.com vs Calendly for self-host needs?", "Add a workflow: booked \u2192 Slack \u2192 CRM task."] as Spec["prompts"],
    prerequisites: ["Calendar connections", "Hosting if self-hosted"],
    tips: ["Routing rules save SDRs.", "Confirm privacy for calendar scopes."],
    stars: "47k",
    group: "sales",
  },
  {
    repo: "chatwoot/chatwoot",
    name: "Chatwoot",
    type: "skill",
    categories: ["sales", "operations", "marketing"] as Category[],
    industries: ["saas", "ecommerce", "agency", "other"] as Industry[],
    blurb: "Open-source customer engagement suite \u2014 live chat, email, shared inbox.",
    exampleIntro: "Support lives in personal inboxes and nothing is measurable.",
    steps: ["Deploy Chatwoot.", "Connect the website widget.", "Create an inbox and SLAs.", "Add canned replies."] as Spec["steps"],
    prompts: ["Deploy Chatwoot for website live chat + email.", "Chatwoot vs Intercom for an early SaaS?", "Canned reply starter pack for onboarding questions."] as Spec["prompts"],
    prerequisites: ["Hosting", "Agent staffing plan"],
    tips: ["Shared inbox needs ownership rules.", "Tag conversations for product insights."],
    stars: "36k",
    group: "sales",
  },
  {
    repo: "medusajs/medusa",
    name: "Medusa",
    type: "skill",
    categories: ["sales", "engineering", "product"] as Category[],
    industries: ["ecommerce", "saas", "other"] as Industry[],
    blurb: "Open-source commerce platform (Node) for building customizable storefronts and admin.",
    exampleIntro: "You need commerce logic you can customize without fighting a hosted monolith day one.",
    steps: ["Install Medusa backend.", "Create products.", "Connect a storefront starter.", "Test checkout on staging."] as Spec["steps"],
    prompts: ["Scaffold a Medusa store for a simple catalog.", "Medusa vs Saleor for our stack?", "Where do we customize checkout?"] as Spec["prompts"],
    prerequisites: ["Node eng", "Postgres etc. per docs", "Payment provider"],
    tips: ["Commerce is detail-heavy \u2014 budget QA.", "Start with a narrow catalog."],
    stars: "36k",
    group: "sales",
  },
  {
    repo: "saleor/saleor",
    name: "Saleor",
    type: "skill",
    categories: ["sales", "engineering", "product"] as Category[],
    industries: ["ecommerce", "marketplace", "other"] as Industry[],
    blurb: "Open-source, API-first GraphQL commerce platform for ambitious storefronts.",
    exampleIntro: "You want headless commerce with a strong API and admin.",
    steps: ["Deploy Saleor.", "Model products/channels.", "Build or connect a storefront against the GraphQL API."] as Spec["steps"],
    prompts: ["Set up Saleor for a multi-channel catalog.", "Saleor vs Medusa for GraphQL-first teams?", "Permissions model overview."] as Spec["prompts"],
    prerequisites: ["Ops + GraphQL comfort", "Storefront eng"],
    tips: ["API-first shines with a real frontend team.", "Plan catalog data quality early."],
    stars: "23k",
    group: "sales",
  },
  {
    repo: "erxes/erxes",
    name: "Erxes",
    type: "skill",
    categories: ["sales", "marketing", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source experience operating system \u2014 messaging, CRM-ish growth tools in one suite.",
    exampleIntro: "A lean team wants chat + CRM-ish tools without five vendors.",
    steps: ["Deploy Erxes.", "Enable the modules you need only.", "Connect channels your customers already use."] as Spec["steps"],
    prompts: ["Which Erxes modules should a 5-person agency enable first?", "Erxes vs Chatwoot + Twenty?", "Onboarding checklist."] as Spec["prompts"],
    prerequisites: ["Hosting", "Scope control"],
    tips: ["Turn off modules you won\u2019t operate.", "Train the team or it becomes shelfware."],
    stars: "4.1k",
    group: "sales",
  },
  {
    repo: "espocrm/espocrm",
    name: "EspoCRM",
    type: "skill",
    categories: ["sales", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Traditional open-source CRM focused on sales pipelines, entities, and customization.",
    exampleIntro: "You need a classic CRM you can self-host and customize.",
    steps: ["Install EspoCRM.", "Configure leads/opportunities.", "Add fields your process needs \u2014 carefully."] as Spec["steps"],
    prompts: ["Configure EspoCRM stages for inbound demo sales.", "EspoCRM vs Twenty for our team?", "Import leads safely."] as Spec["prompts"],
    prerequisites: ["PHP/stack per docs", "CRM admin time"],
    tips: ["Custom fields sprawl \u2014 govern them.", "Reports need clean stage data."],
    stars: "3.2k",
    group: "sales",
  },
  {
    repo: "makeplane/plane",
    name: "Plane",
    type: "skill",
    categories: ["sales", "product", "operations", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source project management (issues, cycles) \u2014 Jira-like without the Jira tax.",
    exampleIntro: "Delivery and sales handoffs die in spreadsheets.",
    steps: ["Deploy Plane.", "Create a project for post-sale onboarding.", "Track issues with owners and due dates."] as Spec["steps"],
    prompts: ["Set up Plane for customer onboarding tasks.", "Plane vs Linear/Jira for a startup?", "Template a sales\u2192CS handoff project."] as Spec["prompts"],
    prerequisites: ["Hosting", "Team agreement on statuses"],
    tips: ["PM tools fail without WIP limits.", "Integrate with Slack notifications lightly."],
    stars: "56k",
    group: "sales",
  },
  {
    repo: "nocodb/nocodb",
    name: "NocoDB",
    type: "skill",
    categories: ["sales", "operations", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source Airtable alternative \u2014 spreadsheets on top of your database/smart tables.",
    exampleIntro: "Ops runs the business in Airtable and IT wants ownership.",
    steps: ["Deploy NocoDB.", "Connect a database or start a base.", "Rebuild one Airtable workflow (pipeline tracker)."] as Spec["steps"],
    prompts: ["Rebuild our deals tracker in NocoDB.", "NocoDB vs Noco/Airtable migration tips?", "Permissions model basics."] as Spec["prompts"],
    prerequisites: ["Hosting", "Data model thinking"],
    tips: ["Spreadsheet UI still needs schema discipline.", "Backups matter."],
    stars: "64k",
    group: "sales",
  },
  {
    repo: "ToolJet/ToolJet",
    name: "ToolJet",
    type: "skill",
    categories: ["sales", "operations", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source low-code platform for internal tools on top of your DBs and APIs.",
    exampleIntro: "Sales/ops wants an admin panel and eng is tired of one-off UIs.",
    steps: ["Deploy ToolJet.", "Connect your DB/API.", "Build a simple leads admin with permissions."] as Spec["steps"],
    prompts: ["Build a ToolJet admin for lead reassignment.", "ToolJet vs Appsmith for internal tools?", "Security checklist for low-code admins."] as Spec["prompts"],
    prerequisites: ["Hosting", "Data source access", "Auth"],
    tips: ["Low-code still needs review.", "Least privilege DB users."],
    stars: "38k",
    group: "sales",
  },
  {
    repo: "coreyhaines31/marketingskills",
    name: "Marketing Skills",
    type: "skill",
    categories: ["marketing", "growth", "sales"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "Corey Haines\u2019 marketing skills pack for Claude \u2014 CRO, copy, SEO, emails, and more.",
    exampleIntro: "Marketing wants Claude to follow real playbooks, not generic \u201cwrite a blog.\u201d",
    steps: ["Install with npx skills add coreyhaines31/marketingskills (or per README).", "Enable only the skills you\u2019ll use weekly.", "Run copywriting or CRO on a real page."] as Spec["steps"],
    prompts: ["Install marketingskills and run cro on our pricing page.", "Which skills matter for a PLG SaaS content engine?", "Combine ai-seo + copywriting on this outline."] as Spec["prompts"],
    prerequisites: ["Claude / Agent Skills host", "Brand/product context"],
    tips: ["Too many skills = context tax \u2014 be selective.", "Deslop before you publish."],
    stars: "44k",
    group: "marketing",
  },
  {
    repo: "hoppscotch/hoppscotch",
    name: "Hoppscotch",
    type: "skill",
    categories: ["engineering", "marketing", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source API development/testing client (Postman alternative) in the browser.",
    exampleIntro: "Marketing/eng integrations break and nobody can replay the API call.",
    steps: ["Use Hoppscotch web or self-host.", "Save a collection for your public API.", "Share examples with partner marketers integrating webhooks."] as Spec["steps"],
    prompts: ["Create a Hoppscotch collection for our public API.", "Hoppscotch vs Postman for open-source teams?", "Document auth examples for partners."] as Spec["prompts"],
    prerequisites: ["API access", "Optional self-host"],
    tips: ["Saved examples beat tribal knowledge.", "Don\u2019t store production secrets in shared collections."],
    stars: "80k",
    group: "marketing",
  },
  {
    repo: "AppFlowy-IO/AppFlowy",
    name: "AppFlowy",
    type: "skill",
    categories: ["marketing", "operations", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source Notion-style workspace for docs and project wiki you can self-host.",
    exampleIntro: "Marketing knowledge lives in random Notion pages with no ownership story.",
    steps: ["Install AppFlowy.", "Create a Marketing Wiki space.", "Move the top 10 living docs first \u2014 not everything."] as Spec["steps"],
    prompts: ["Structure an AppFlowy wiki for content ops.", "AppFlowy vs Notion for a privacy-sensitive team?", "Migration plan for 10 critical docs."] as Spec["prompts"],
    prerequisites: ["Desktop/self-host willingness", "Doc owners"],
    tips: ["Migrate ruthlessly \u2014 archive the rest.", "Templates > blank pages."],
    stars: "75k",
    group: "marketing",
  },
  {
    repo: "strapi/strapi",
    name: "Strapi",
    type: "skill",
    categories: ["marketing", "engineering", "product"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "Leading open-source headless CMS for content APIs marketers and devs share.",
    exampleIntro: "The marketing site is hardcoded and every copy change needs an eng ticket.",
    steps: ["Deploy Strapi.", "Model Blog/Page types.", "Connect Next.js (or your site) to the API.", "Give marketers roles carefully."] as Spec["steps"],
    prompts: ["Model a blog content type in Strapi for our Next site.", "Strapi vs Payload vs Directus for our team?", "Roles for marketers without breaking schema."] as Spec["prompts"],
    prerequisites: ["Hosting", "Content model design", "Frontend eng"],
    tips: ["Content modeling is product work.", "Preview workflows prevent surprises."],
    stars: "73k",
    group: "marketing",
  },
  {
    repo: "appsmithorg/appsmith",
    name: "Appsmith",
    type: "skill",
    categories: ["marketing", "operations", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source platform to build internal admin apps quickly on APIs/DBs.",
    exampleIntro: "Campaign ops needs an internal UI eng doesn\u2019t want to maintain forever.",
    steps: ["Deploy Appsmith.", "Connect a data source.", "Build a campaign checklist app."] as Spec["steps"],
    prompts: ["Build an Appsmith app for campaign QA checklists.", "Appsmith vs ToolJet?", "Auth and audit tips."] as Spec["prompts"],
    prerequisites: ["Hosting", "Data sources"],
    tips: ["Internal tools need owners too.", "Start with read-heavy screens."],
    stars: "41k",
    group: "marketing",
  },
  {
    repo: "payloadcms/payload",
    name: "Payload CMS",
    type: "skill",
    categories: ["marketing", "engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Code-first TypeScript headless CMS that lives in your Next.js/node world.",
    exampleIntro: "You want CMS in-repo with TypeScript, not a separate PHP island.",
    steps: ["Add Payload to your app per docs.", "Define collections in code.", "Give editors access to the admin."] as Spec["steps"],
    prompts: ["Add a Payload posts collection to our Next app.", "Payload vs Strapi for TypeScript teams?", "Access control patterns."] as Spec["prompts"],
    prerequisites: ["TypeScript eng", "Hosting story"],
    tips: ["Code-first is a feature for eng-led content models.", "Still design editor UX kindly."],
    stars: "44k",
    group: "marketing",
  },
  {
    repo: "directus/directus",
    name: "Directus",
    type: "skill",
    categories: ["marketing", "engineering", "operations"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source data platform / CMS wrapping your SQL database with APIs and an admin UI.",
    exampleIntro: "You already have a database and need an admin/content UI without rewriting it.",
    steps: ["Point Directus at your DB (carefully).", "Configure collections/permissions.", "Let ops edit allowed fields only."] as Spec["steps"],
    prompts: ["Wrap our Postgres content tables with Directus.", "Directus vs Strapi when DB already exists?", "Permission model pitfalls."] as Spec["prompts"],
    prerequisites: ["SQL database", "Strong backups before connecting"],
    tips: ["Never give editors raw destructive rights casually.", "Schema changes need eng partnership."],
    stars: "37k",
    group: "marketing",
  },
  {
    repo: "Budibase/budibase",
    name: "Budibase",
    type: "skill",
    categories: ["marketing", "operations", "engineering"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Open-source low-code platform for internal tools and approval apps.",
    exampleIntro: "Marketing ops needs forms/approvals without a custom app each time.",
    steps: ["Deploy Budibase.", "Build an approval app for campaign launches.", "Connect notifications to Slack/email."] as Spec["steps"],
    prompts: ["Build a Budibase approval flow for launch checklists.", "Budibase vs ToolJet for non-eng builders?", "When to graduate to custom code?"] as Spec["prompts"],
    prerequisites: ["Hosting", "Process clarity"],
    tips: ["Low-code apps become critical path \u2014 treat them seriously.", "Version and backup."],
    stars: "28k",
    group: "marketing",
  },
  {
    repo: "mailchimp/email-blueprints",
    name: "Email Blueprints",
    type: "skill",
    categories: ["marketing"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "Mailchimp\u2019s open email templates/blueprints for building better HTML emails.",
    exampleIntro: "Every campaign reinvents broken HTML email layouts.",
    steps: ["Browse the blueprints.", "Fork a layout that matches your campaign type.", "Adapt styles to brand; test in major clients."] as Spec["steps"],
    prompts: ["Pick an email blueprint for a product launch newsletter.", "How do we adapt blueprints to our brand CSS constraints?", "Checklist for testing HTML email."] as Spec["prompts"],
    prerequisites: ["ESP or HTML email send path", "Design/brand assets"],
    tips: ["HTML email is still table hell \u2014 test litmus/clients.", "Keep templates versioned."],
    stars: "7.0k",
    group: "marketing",
  },
  {
    repo: "aitytech/agentkits-marketing",
    name: "Agentkits Marketing",
    type: "skill",
    categories: ["marketing", "growth"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Marketing-focused agent kits / skills to run repeatable GTM workflows with AI agents.",
    exampleIntro: "You want packaged marketing agent workflows, not blank chat.",
    steps: ["Clone the repo.", "Install the kits that match your motion (content, ads, etc.).", "Run one kit on a real campaign with review gates."] as Spec["steps"],
    prompts: ["Which agentkits-marketing workflows fit a PLG launch?", "Turn this kit into our team\u2019s weekly cadence.", "Where must humans approve outputs?"] as Spec["prompts"],
    prerequisites: ["Agent host", "Brand context", "Review SLA"],
    tips: ["Kits are accelerators \u2014 brand voice still required.", "Measure outcomes, not just output volume."],
    stars: "~600",
    group: "marketing",
  },
  {
    repo: "sindresorhus/awesome",
    name: "Awesome",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "The meta-list of curated awesome lists across every tech topic.",
    exampleIntro: "You don\u2019t know which awesome-* list to open for a new problem space.",
    steps: ["Start at sindresorhus/awesome.", "Jump to the topic list you need.", "Pick 1\u20132 tools to evaluate, not 20."] as Spec["steps"],
    prompts: ["Find awesome lists for LLMOps.", "How should we use awesome lists without rabbit-holing?", "Pick a shortlist for our stack decision."] as Spec["prompts"],
    prerequisites: ["Timebox browsing"],
    tips: ["Awesome lists are maps \u2014 not to-do lists.", "Timebox research."],
    stars: "494k",
    group: "development",
  },
  {
    repo: "freeCodeCamp/freeCodeCamp",
    name: "freeCodeCamp",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "other"] as Industry[],
    blurb: "Massive open learning platform and curriculum for coding \u2014 free certifications and projects.",
    exampleIntro: "A teammate needs to learn to code without an expensive bootcamp.",
    steps: ["Create a freeCodeCamp account / clone as needed.", "Pick a certification track.", "Ship the projects; review together."] as Spec["steps"],
    prompts: ["Which freeCodeCamp cert fits a marketer moving into ops scripting?", "Build a 30-day learning plan from freeCodeCamp.", "How do we mentor someone through the first cert?"] as Spec["prompts"],
    prerequisites: ["Consistency", "Mentor optional but helpful"],
    tips: ["Projects > passive watching.", "Celebrate shipped projects publicly on the team."],
    stars: "454k",
    group: "development",
  },
  {
    repo: "donnemartin/system-design-primer",
    name: "System Design Primer",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "education", "other"] as Industry[],
    blurb: "The classic open primer for learning system design interviews and real architecture basics.",
    exampleIntro: "You\u2019re designing a feature that needs scale thinking, not just CRUD.",
    steps: ["Read the primer sections relevant to your problem.", "Sketch your design.", "Review with a senior against the primer checklists."] as Spec["steps"],
    prompts: ["Using the system-design-primer, outline a design for our notifications system.", "What primer topics matter for a multi-tenant SaaS?", "Quiz me on caching tradeoffs."] as Spec["prompts"],
    prerequisites: ["Basic backend literacy"],
    tips: ["Primer knowledge \u2260 your constraints \u2014 adapt.", "Draw diagrams."],
    stars: "363k",
    group: "development",
  },
  {
    repo: "kamranahmedse/developer-roadmap",
    name: "Developer Roadmap",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Visual roadmaps for frontend, backend, DevOps, and more \u2014 what to learn next.",
    exampleIntro: "Juniors ask \u201cwhat should I learn?\u201d and get chaotic Slack answers.",
    steps: ["Open roadmap.sh / the repo.", "Pick a path.", "Turn the next 3 nodes into a month plan with projects."] as Spec["steps"],
    prompts: ["Build a 90-day frontend roadmap for our junior hire.", "Which roadmap fits a growth engineer?", "How do we adapt roadmaps to our stack?"] as Spec["prompts"],
    prerequisites: ["Honest assessment of current level"],
    tips: ["Roadmaps are menus \u2014 don\u2019t try to eat everything.", "Projects lock learning in."],
    stars: "364k",
    group: "development",
  },
  {
    repo: "facebook/react",
    name: "React",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "The library for web and native UI components \u2014 the default frontend skill for modern product teams.",
    exampleIntro: "You\u2019re hiring / training people who will ship UI in the React ecosystem.",
    steps: ["Follow the official docs tutorial.", "Build a small component in your design system.", "Learn hooks + data fetching patterns your team uses."] as Spec["steps"],
    prompts: ["Explain React server components vs client components for our Next app.", "Refactor this class component to hooks.", "React learning path for a strong designer moving to code."] as Spec["prompts"],
    prerequisites: ["JS fundamentals"],
    tips: ["Learn your team\u2019s React conventions, not every pattern on Twitter.", "Pair with your component library."],
    stars: "247k",
    group: "development",
  },
  {
    repo: "torvalds/linux",
    name: "Linux",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "The Linux kernel \u2014 foundation of servers, containers, and most production infrastructure.",
    exampleIntro: "You\u2019re debugging production and need to understand the OS under your containers.",
    steps: ["You don\u2019t \u201cinstall Linux\u201d from this repo for app work \u2014 use a distro.", "Read kernel docs when debugging deep issues.", "For learning, run Linux VMs and practice systemd, networking, permissions."] as Spec["steps"],
    prompts: ["What should an app eng know about Linux for production debugging?", "How do containers relate to the Linux kernel?", "Practical Linux checklist for SaaS on-call."] as Spec["prompts"],
    prerequisites: ["A Linux environment to practice"],
    tips: ["This repo is the kernel \u2014 daily work uses distros.", "Learn observability tools next."],
    stars: "242k",
    group: "development",
  },
  {
    repo: "vuejs/vue",
    name: "Vue",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "agency", "other"] as Industry[],
    blurb: "Progressive JavaScript framework for building UIs \u2014 approachable alternative in the frontend ecosystem.",
    exampleIntro: "Your team prefers Vue or maintains a Vue codebase.",
    steps: ["Follow vuejs.org tutorial.", "Build a small feature in Vue 3 + your state pattern.", "Align with composition API conventions your team picked."] as Spec["steps"],
    prompts: ["Vue 3 composition API primer for React engineers.", "When to choose Vue vs React for a greenfield app?", "Migrate a component to script setup."] as Spec["prompts"],
    prerequisites: ["JS fundamentals"],
    tips: ["Match the Vue major version your repo uses.", "Ecosystem choices (Nuxt) matter."],
    stars: "210k",
    group: "development",
  },
  {
    repo: "trekhleb/javascript-algorithms",
    name: "JavaScript Algorithms",
    type: "skill",
    categories: ["engineering", "other"] as Category[],
    industries: ["education", "saas", "other"] as Industry[],
    blurb: "Algorithms and data structures implemented in JavaScript with explanations.",
    exampleIntro: "Interview prep or fundamentals refresh without switching languages.",
    steps: ["Browse the topic you need.", "Implement the exercise yourself before reading solutions.", "Discuss Big-O in a pairing session."] as Spec["steps"],
    prompts: ["Help me practice two-sum using this repo\u2019s style.", "Which structures matter most for frontend eng interviews?", "Study plan for 2 weeks."] as Spec["prompts"],
    prerequisites: ["JS comfort"],
    tips: ["Understanding > memorizing code.", "Tie algorithms back to real perf issues occasionally."],
    stars: "196k",
    group: "development",
  },
  {
    repo: "microsoft/vscode",
    name: "VS Code",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "The open-source code editor that powers VS Code \u2014 extensions, debugging, remote dev.",
    exampleIntro: "Your team lives in VS Code and wants consistent editor setup.",
    steps: ["Install VS Code.", "Share a recommended extensions list.", "Add repo `.vscode` settings for format-on-save."] as Spec["steps"],
    prompts: ["Recommend a VS Code extension pack for our TS monorepo.", "How do we standardize settings.json for the team?", "Remote SSH development tips."] as Spec["prompts"],
    prerequisites: ["Desktop install"],
    tips: ["Check in useful .vscode metadata; don\u2019t force themes.", "Extensions can slow the editor \u2014 be selective."],
    stars: "189k",
    group: "development",
  },
  {
    repo: "vercel/next.js",
    name: "Next.js",
    type: "skill",
    categories: ["engineering", "product", "marketing"] as Category[],
    industries: ["saas", "agency", "ecommerce", "other"] as Industry[],
    blurb: "React framework for production \u2014 routing, SSR/SSG, and full-stack patterns used across modern SaaS.",
    exampleIntro: "You\u2019re building a product site/app and want the default React production stack.",
    steps: ["Create a Next.js app.", "Ship one route with data fetching.", "Learn your deployment target (Vercel or elsewhere)."] as Spec["steps"],
    prompts: ["Scaffold a Next.js app for our marketing site + app shell.", "App Router patterns we should standardize?", "SEO metadata checklist in Next.js."] as Spec["prompts"],
    prerequisites: ["Node + React literacy"],
    tips: ["Follow the current App Router docs \u2014 old pages tutorials confuse.", "Performance and caching are features \u2014 learn them."],
    stars: "142k",
    group: "development",
  },
  {
    repo: "golang/go",
    name: "Go",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "The Go programming language \u2014 simple, great for APIs, CLIs, and cloud services.",
    exampleIntro: "You\u2019re writing backend services and want a language built for that job.",
    steps: ["Install Go.", "Work through A Tour of Go.", "Write a tiny HTTP service and deploy it."] as Spec["steps"],
    prompts: ["Go learning path for a Node engineer.", "When is Go a better fit than Node for our workers?", "Idiomatic error handling primer."] as Spec["prompts"],
    prerequisites: ["Willingness to learn new syntax"],
    tips: ["Idiomatic Go \u2260 translating TypeScript line-by-line.", "Use gofmt; don\u2019t fight it."],
    stars: "136k",
    group: "development",
  },
  {
    repo: "kubernetes/kubernetes",
    name: "Kubernetes",
    type: "skill",
    categories: ["engineering", "operations"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Production-grade container orchestration \u2014 the default for serious multi-service ops.",
    exampleIntro: "You\u2019ve outgrown single-host Docker and need orchestration (maybe).",
    steps: ["Don\u2019t start with full K8s if a PaaS is enough.", "If you need it: use a managed cluster.", "Deploy one service with health checks and resource limits."] as Spec["steps"],
    prompts: ["Do we need Kubernetes yet for our stage?", "Minimal safe K8s checklist for one web service.", "Explain pods/deployments/services simply."] as Spec["prompts"],
    prerequisites: ["Ops capacity", "Containerized apps"],
    tips: ["K8s complexity is real \u2014 managed + platform eng helps.", "Start with good Docker images first."],
    stars: "124k",
    group: "development",
  },
  {
    repo: "rust-lang/rust",
    name: "Rust",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Rust language \u2014 performance and safety for systems, CLIs, and performance-critical services.",
    exampleIntro: "You need speed/safety beyond typical dynamic languages for a component.",
    steps: ["Install Rust via rustup.", "Do the Book\u2019s early chapters.", "Write a small CLI that solves a real internal pain."] as Spec["steps"],
    prompts: ["Rust learning path for a TypeScript eng.", "When is Rust worth it in a SaaS stack?", "First CLI project ideas for our team."] as Spec["prompts"],
    prerequisites: ["Patience with the borrow checker"],
    tips: ["Don\u2019t rewrite the world in Rust.", "Great for isolated performance-critical pieces."],
    stars: "115k",
    group: "development",
  },
  {
    repo: "denoland/deno",
    name: "Deno",
    type: "skill",
    categories: ["engineering"] as Category[],
    industries: ["saas", "other"] as Industry[],
    blurb: "Modern JS/TS runtime with secure defaults, tooling, and web-standard APIs.",
    exampleIntro: "You\u2019re exploring an alternative to Node with batteries included.",
    steps: ["Install Deno.", "Run a script with explicit permissions.", "Evaluate for CLIs or edge-style workloads."] as Spec["steps"],
    prompts: ["Deno vs Node for a new TS CLI?", "Explain Deno permissions model simply.", "Migrate a tiny Node script to Deno."] as Spec["prompts"],
    prerequisites: ["TS comfort"],
    tips: ["Ecosystem differences matter \u2014 check library support.", "Permissions are a feature \u2014 use them."],
    stars: "108k",
    group: "development",
  },
  {
    repo: "supabase/supabase",
    name: "Supabase",
    type: "skill",
    categories: ["engineering", "product"] as Category[],
    industries: ["saas", "marketplace", "other"] as Industry[],
    blurb: "Open-source Firebase alternative \u2014 Postgres, auth, storage, realtime, and studio UI.",
    exampleIntro: "You want a backend fast without giving up SQL.",
    steps: ["Create a Supabase project.", "Model tables.", "Add auth + row-level security before launch.", "Connect from your Next app."] as Spec["steps"],
    prompts: ["Model a multi-tenant schema in Supabase with RLS.", "Supabase vs custom Node+Postgres for our MVP?", "Auth + RLS starter checklist."] as Spec["prompts"],
    prerequisites: ["Product schema thinking", "Security review for RLS"],
    tips: ["RLS is mandatory for multi-tenant.", "Don\u2019t disable security \u201cjust for now.\u201d"],
    stars: "108k",
    group: "development",
  },
];

export const GITHUB_CATALOG_RESOURCES: DirectoryEntry[] = SPECS.map(entryFromSpec);
